/*!
 * jQuery JavaScript Library v1.4.5pre
 * http://jquery.com/
 *
 * Copyright 2010, John Resig
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * Includes Sizzle.js
 * http://sizzlejs.com/
 * Copyright 2010, The Dojo Foundation
 * Released under the MIT, BSD, and GPL Licenses.
 *
 * Date: Thu Nov 11 19:05:10 2010 -0500
 */
(function(J,E){var y=J.document,K=function(){function b(){if(!n.isReady){try{y.documentElement.doScroll("left")}catch(f){setTimeout(b,1);return}n.ready()}}var n=function(f,w){return new n.fn.init(f,w)},C=J.jQuery,D=J.$,l,r=/^(?:[^<]*(<[\w\W]+>)[^>]*$|#([\w\-]+)$)/,u=/\S/,t=/^\s+/,e=/\s+$/,h=/\W/,m=/\d/,o=/^<(\w+)\s*\/?>(?:<\/\1>)?$/,v=/^[\],:{}\s]*$/,i=/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,q=/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,j=/(?:^|:|,)(?:\s*\[)+/g,s=/(webkit)[ \/]([\w.]+)/,
a=/(opera)(?:.*version)?[ \/]([\w.]+)/,c=/(msie) ([\w.]+)/,d=/(mozilla)(?:.*? rv:([\w.]+))?/,g=navigator.userAgent,k=false,p=[],x,A=Object.prototype.toString,G=Object.prototype.hasOwnProperty,M=Array.prototype.push,N=Array.prototype.slice,O=String.prototype.trim,F=Array.prototype.indexOf,Q={};n.fn=n.prototype={init:function(f,w){var z,B,I;if(!f)return this;if(f.nodeType){this.context=this[0]=f;this.length=1;return this}if(f==="body"&&!w&&y.body){this.context=y;this[0]=y.body;this.selector="body";
this.length=1;return this}if(typeof f==="string")if((z=r.exec(f))&&(z[1]||!w))if(z[1]){I=w?w.ownerDocument||w:y;if(B=o.exec(f))if(n.isPlainObject(w)){f=[y.createElement(B[1])];n.fn.attr.call(f,w,true)}else f=[I.createElement(B[1])];else{B=n.buildFragment([z[1]],[I]);f=(B.cacheable?B.fragment.cloneNode(true):B.fragment).childNodes}return n.merge(this,f)}else{if((B=y.getElementById(z[2]))&&B.parentNode){if(B.id!==z[2])return l.find(f);this.length=1;this[0]=B}this.context=y;this.selector=f;return this}else if(!w&&
!h.test(f)){this.selector=f;this.context=y;f=y.getElementsByTagName(f);return n.merge(this,f)}else return!w||w.jquery?(w||l).find(f):n(w).find(f);else if(n.isFunction(f))return l.ready(f);if(f.selector!==E){this.selector=f.selector;this.context=f.context}return n.makeArray(f,this)},selector:"",jquery:"1.4.5pre",length:0,size:function(){return this.length},toArray:function(){return N.call(this,0)},get:function(f){return f==null?this.toArray():f<0?this.slice(f)[0]:this[f]},pushStack:function(f,w,z){var B=
n();n.isArray(f)?M.apply(B,f):n.merge(B,f);B.prevObject=this;B.context=this.context;if(w==="find")B.selector=this.selector+(this.selector?" ":"")+z;else if(w)B.selector=this.selector+"."+w+"("+z+")";return B},each:function(f,w){return n.each(this,f,w)},ready:function(f){n.bindReady();if(n.isReady)f.call(y,n);else p&&p.push(f);return this},eq:function(f){return f===-1?this.slice(f):this.slice(f,+f+1)},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},slice:function(){return this.pushStack(N.apply(this,
arguments),"slice",N.call(arguments).join(","))},map:function(f){return this.pushStack(n.map(this,function(w,z){return f.call(w,z,w)}))},end:function(){return this.prevObject||n(null)},push:M,sort:[].sort,splice:[].splice};n.fn.init.prototype=n.fn;n.extend=n.fn.extend=function(){var f,w,z,B,I,H=arguments[0]||{},L=1,P=arguments.length,R=false;if(typeof H==="boolean"){R=H;H=arguments[1]||{};L=2}if(typeof H!=="object"&&!n.isFunction(H))H={};if(P===L){H=this;--L}for(;L<P;L++)if((f=arguments[L])!=null)for(w in f){z=
H[w];B=f[w];if(H!==B)if(R&&B&&(n.isPlainObject(B)||(I=n.isArray(B)))){if(I){I=false;z=z&&n.isArray(z)?z:[]}else z=z&&n.isPlainObject(z)?z:{};H[w]=n.extend(R,z,B)}else if(B!==E)H[w]=B}return H};n.extend({noConflict:function(f){J.$=D;if(f)J.jQuery=C;return n},isReady:false,readyWait:1,ready:function(f){f===true&&n.readyWait--;if(!n.readyWait||f!==true&&!n.isReady){if(!y.body)return setTimeout(n.ready,1);n.isReady=true;if(!(f!==true&&--n.readyWait>0))if(p){var w=0,z=p;for(p=null;f=z[w++];)f.call(y,n);
n.fn.trigger&&n(y).trigger("ready").unbind("ready")}}},bindReady:function(){if(!k){k=true;if(y.readyState==="complete")return setTimeout(n.ready,1);if(y.addEventListener){y.addEventListener("DOMContentLoaded",x,false);J.addEventListener("load",n.ready,false)}else if(y.attachEvent){y.attachEvent("onreadystatechange",x);J.attachEvent("onload",n.ready);var f=false;try{f=J.frameElement==null}catch(w){}y.documentElement.doScroll&&f&&b()}}},isFunction:function(f){return n.type(f)==="function"},isArray:Array.isArray||
function(f){return n.type(f)==="array"},isWindow:function(f){return f&&typeof f==="object"&&"setInterval"in f},isNaN:function(f){return f==null||!m.test(f)||isNaN(f)},type:function(f){return f==null?String(f):Q[A.call(f)]||"object"},isPlainObject:function(f){if(!f||n.type(f)!=="object"||f.nodeType||n.isWindow(f))return false;if(f.constructor&&!G.call(f,"constructor")&&!G.call(f.constructor.prototype,"isPrototypeOf"))return false;for(var w in f);return w===E||G.call(f,w)},isEmptyObject:function(f){for(var w in f)return false;
return true},error:function(f){throw f;},parseJSON:function(f){if(typeof f!=="string"||!f)return null;f=n.trim(f);if(v.test(f.replace(i,"@").replace(q,"]").replace(j,"")))return J.JSON&&J.JSON.parse?J.JSON.parse(f):(new Function("return "+f))();else n.error("Invalid JSON: "+f)},noop:function(){},globalEval:function(f){if(f&&u.test(f)){var w=y.getElementsByTagName("head")[0]||y.documentElement,z=y.createElement("script");z.type="text/javascript";if(n.support.scriptEval)z.appendChild(y.createTextNode(f));
else z.text=f;w.insertBefore(z,w.firstChild);w.removeChild(z)}},nodeName:function(f,w){return f.nodeName&&f.nodeName.toUpperCase()===w.toUpperCase()},each:function(f,w,z){var B,I=0,H=f.length,L=H===E||n.isFunction(f);if(z)if(L)for(B in f){if(w.apply(f[B],z)===false)break}else for(;I<H;){if(w.apply(f[I++],z)===false)break}else if(L)for(B in f){if(w.call(f[B],B,f[B])===false)break}else for(z=f[0];I<H&&w.call(z,I,z)!==false;z=f[++I]);return f},trim:O?function(f){return f==null?"":O.call(f)}:function(f){return f==
null?"":f.toString().replace(t,"").replace(e,"")},makeArray:function(f,w){var z=w||[];if(f!=null){var B=n.type(f);f.length==null||B==="string"||B==="function"||B==="regexp"||n.isWindow(f)?M.call(z,f):n.merge(z,f)}return z},inArray:function(f,w){if(w.indexOf)return w.indexOf(f);for(var z=0,B=w.length;z<B;z++)if(w[z]===f)return z;return-1},merge:function(f,w){var z=f.length,B=0;if(typeof w.length==="number")for(var I=w.length;B<I;B++)f[z++]=w[B];else for(;w[B]!==E;)f[z++]=w[B++];f.length=z;return f},
grep:function(f,w,z){var B=[],I;z=!!z;for(var H=0,L=f.length;H<L;H++){I=!!w(f[H],H);z!==I&&B.push(f[H])}return B},map:function(f,w,z){for(var B=[],I,H=0,L=f.length;H<L;H++){I=w(f[H],H,z);if(I!=null)B[B.length]=I}return B.concat.apply([],B)},guid:1,proxy:function(f,w,z){if(arguments.length===2)if(typeof w==="string"){z=f;f=z[w];w=E}else if(w&&!n.isFunction(w)){z=w;w=E}if(!w&&f)w=function(){return f.apply(z||this,arguments)};if(f)w.guid=f.guid=f.guid||w.guid||n.guid++;return w},access:function(f,w,
z,B,I,H){var L=f.length;if(typeof w==="object"){for(var P in w)n.access(f,P,w[P],B,I,z);return f}if(z!==E){B=!H&&B&&n.isFunction(z);for(P=0;P<L;P++)I(f[P],w,B?z.call(f[P],P,I(f[P],w)):z,H);return f}return L?I(f[0],w):E},now:function(){return(new Date).getTime()},uaMatch:function(f){f=f.toLowerCase();f=s.exec(f)||a.exec(f)||c.exec(f)||f.indexOf("compatible")<0&&d.exec(f)||[];return{browser:f[1]||"",version:f[2]||"0"}},browser:{}});n.each("Boolean Number String Function Array Date RegExp Object".split(" "),
function(f,w){Q["[object "+w+"]"]=w.toLowerCase()});g=n.uaMatch(g);if(g.browser){n.browser[g.browser]=true;n.browser.version=g.version}if(n.browser.webkit)n.browser.safari=true;if(F)n.inArray=function(f,w){return F.call(w,f)};if(!/\s/.test("\u00a0")){t=/^[\s\xA0]+/;e=/[\s\xA0]+$/}l=n(y);if(y.addEventListener)x=function(){y.removeEventListener("DOMContentLoaded",x,false);n.ready()};else if(y.attachEvent)x=function(){if(y.readyState==="complete"){y.detachEvent("onreadystatechange",x);n.ready()}};return J.jQuery=
J.$=n}();(function(b){(function(){b.support={};var n=y.documentElement,C=y.createElement("script"),D=y.createElement("div"),l="script"+b.now();D.style.display="none";D.innerHTML="   <link/><table></table><a href='/a' style='color:red;float:left;opacity:.55;'>a</a><input type='checkbox'/>";var r=D.getElementsByTagName("*"),u=D.getElementsByTagName("a")[0],t=y.createElement("select"),e=t.appendChild(y.createElement("option"));if(!(!r||!r.length||!u)){b.support={leadingWhitespace:D.firstChild.nodeType===
3,tbody:!D.getElementsByTagName("tbody").length,htmlSerialize:!!D.getElementsByTagName("link").length,style:/red/.test(u.getAttribute("style")),hrefNormalized:u.getAttribute("href")==="/a",opacity:/^0.55$/.test(u.style.opacity),cssFloat:!!u.style.cssFloat,checkOn:D.getElementsByTagName("input")[0].value==="on",optSelected:e.selected,deleteExpando:true,optDisabled:false,checkClone:false,scriptEval:false,noCloneEvent:true,boxModel:null,inlineBlockNeedsLayout:false,shrinkWrapBlocks:false,reliableHiddenOffsets:true};
t.disabled=true;b.support.optDisabled=!e.disabled;C.type="text/javascript";try{C.appendChild(y.createTextNode("window."+l+"=1;"))}catch(h){}n.insertBefore(C,n.firstChild);if(J[l]){b.support.scriptEval=true;delete J[l]}try{delete C.test}catch(m){b.support.deleteExpando=false}n.removeChild(C);if(D.attachEvent&&D.fireEvent){D.attachEvent("onclick",function o(){b.support.noCloneEvent=false;D.detachEvent("onclick",o)});D.cloneNode(true).fireEvent("onclick")}D=y.createElement("div");D.innerHTML="<input type='radio' name='radiotest' checked='checked'/>";
n=y.createDocumentFragment();n.appendChild(D.firstChild);b.support.checkClone=n.cloneNode(true).cloneNode(true).lastChild.checked;b(function(){var o=y.createElement("div");o.style.width=o.style.paddingLeft="1px";y.body.appendChild(o);b.boxModel=b.support.boxModel=o.offsetWidth===2;if("zoom"in o.style){o.style.display="inline";o.style.zoom=1;b.support.inlineBlockNeedsLayout=o.offsetWidth===2;o.style.display="";o.innerHTML="<div style='width:4px;'></div>";b.support.shrinkWrapBlocks=o.offsetWidth!==
2}o.innerHTML="<table><tr><td style='padding:0;display:none'></td><td>t</td></tr></table>";var v=o.getElementsByTagName("td");b.support.reliableHiddenOffsets=v[0].offsetHeight===0;v[0].style.display="";v[1].style.display="none";b.support.reliableHiddenOffsets=b.support.reliableHiddenOffsets&&v[0].offsetHeight===0;o.innerHTML="";y.body.removeChild(o).style.display="none"});n=function(o){var v=y.createElement("div");o="on"+o;var i=o in v;if(!i){v.setAttribute(o,"return;");i=typeof v[o]==="function"}return i};
b.support.submitBubbles=n("submit");b.support.changeBubbles=n("change");n=C=D=r=u=null}})()})(K);(function(b){function n(l,r,u){if(u===E&&l.nodeType===1){u=l.getAttribute("data-"+r);if(typeof u==="string"){try{u=u==="true"?true:u==="false"?false:u==="null"?null:!b.isNaN(u)?parseFloat(u):D.test(u)?b.parseJSON(u):u}catch(t){}b.data(l,r,u)}else u=E}return u}var C={},D=/^(?:\{.*\}|\[.*\])$/;b.extend({cache:{},uuid:0,expando:"jQuery"+b.now(),noData:{embed:true,object:"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000",
applet:true},data:function(l,r,u){if(b.acceptData(l)){l=l==J?C:l;var t=l.nodeType,e=t?l[b.expando]:null,h=b.cache;if(!(t&&!e&&typeof r==="string"&&u===E)){if(t)e||(l[b.expando]=e=++b.uuid);else h=l;if(typeof r==="object")if(t)h[e]=b.extend(h[e],r);else b.extend(h,r);else if(t&&!h[e])h[e]={};l=t?h[e]:h;if(u!==E)l[r]=u;return typeof r==="string"?l[r]:l}}},removeData:function(l,r){if(b.acceptData(l)){l=l==J?C:l;var u=l.nodeType,t=u?l[b.expando]:l,e=b.cache,h=u?e[t]:t;if(r){if(h){delete h[r];u&&b.isEmptyObject(h)&&
b.removeData(l)}}else if(u&&b.support.deleteExpando)delete l[b.expando];else if(l.removeAttribute)l.removeAttribute(b.expando);else if(u)delete e[t];else for(var m in l)delete l[m]}},acceptData:function(l){if(l.nodeName){var r=b.noData[l.nodeName.toLowerCase()];if(r)return!(r===true||l.getAttribute("classid")!==r)}return true}});b.fn.extend({data:function(l,r){var u=null;if(typeof l==="undefined"){if(this.length){var t=this[0].attributes,e;u=b.data(this[0]);for(var h=0,m=t.length;h<m;h++){e=t[h].name;
if(e.indexOf("data-")===0){e=e.substr(5);n(this[0],e,u[e])}}}return u}else if(typeof l==="object")return this.each(function(){b.data(this,l)});var o=l.split(".");o[1]=o[1]?"."+o[1]:"";if(r===E){u=this.triggerHandler("getData"+o[1]+"!",[o[0]]);if(u===E&&this.length){u=b.data(this[0],l);u=n(this[0],l,u)}return u===E&&o[1]?this.data(o[0]):u}else return this.each(function(){var v=b(this),i=[o[0],r];v.triggerHandler("setData"+o[1]+"!",i);b.data(this,l,r);v.triggerHandler("changeData"+o[1]+"!",i)})},removeData:function(l){return this.each(function(){b.removeData(this,
l)})}})})(K);(function(b){b.extend({queue:function(n,C,D){if(n){C=(C||"fx")+"queue";var l=b.data(n,C);if(!D)return l||[];if(!l||b.isArray(D))l=b.data(n,C,b.makeArray(D));else l.push(D);return l}},dequeue:function(n,C){C=C||"fx";var D=b.queue(n,C),l=D.shift();if(l==="inprogress")l=D.shift();if(l){C==="fx"&&D.unshift("inprogress");l.call(n,function(){b.dequeue(n,C)})}}});b.fn.extend({queue:function(n,C){if(typeof n!=="string"){C=n;n="fx"}if(C===E)return b.queue(this[0],n);return this.each(function(){var D=
b.queue(this,n,C);n==="fx"&&D[0]!=="inprogress"&&b.dequeue(this,n)})},dequeue:function(n){return this.each(function(){b.dequeue(this,n)})},delay:function(n,C){n=b.fx?b.fx.speeds[n]||n:n;C=C||"fx";return this.queue(C,function(){var D=this;setTimeout(function(){b.dequeue(D,C)},n)})},clearQueue:function(n){return this.queue(n||"fx",[])}})})(K);(function(b){var n=/[\n\t]/g,C=/\s+/,D=/\r/g,l=/^(?:href|src|style)$/,r=/^(?:button|input)$/i,u=/^(?:button|input|object|select|textarea)$/i,t=/^a(?:rea)?$/i,
e=/^(?:radio|checkbox)$/i;b.props={"for":"htmlFor","class":"className",readonly:"readOnly",maxlength:"maxLength",cellspacing:"cellSpacing",rowspan:"rowSpan",colspan:"colSpan",tabindex:"tabIndex",usemap:"useMap",frameborder:"frameBorder"};b.fn.extend({attr:function(h,m){return b.access(this,h,m,true,b.attr)},removeAttr:function(h){return this.each(function(){b.attr(this,h,"");this.nodeType===1&&this.removeAttribute(h)})},addClass:function(h){if(b.isFunction(h))return this.each(function(c){var d=b(this);
d.addClass(h.call(this,c,d.attr("class")))});if(h&&typeof h==="string")for(var m=(h||"").split(C),o=0,v=this.length;o<v;o++){var i=this[o];if(i.nodeType===1)if(i.className){for(var q=" "+i.className+" ",j=i.className,s=0,a=m.length;s<a;s++)if(q.indexOf(" "+m[s]+" ")<0)j+=" "+m[s];i.className=b.trim(j)}else i.className=h}return this},removeClass:function(h){if(b.isFunction(h))return this.each(function(a){var c=b(this);c.removeClass(h.call(this,a,c.attr("class")))});if(h&&typeof h==="string"||h===E)for(var m=
(h||"").split(C),o=0,v=this.length;o<v;o++){var i=this[o];if(i.nodeType===1&&i.className)if(h){for(var q=(" "+i.className+" ").replace(n," "),j=0,s=m.length;j<s;j++)q=q.replace(" "+m[j]+" "," ");i.className=b.trim(q)}else i.className=""}return this},toggleClass:function(h,m){var o=typeof h,v=typeof m==="boolean";if(b.isFunction(h))return this.each(function(i){var q=b(this);q.toggleClass(h.call(this,i,q.attr("class"),m),m)});return this.each(function(){if(o==="string")for(var i,q=0,j=b(this),s=m,a=
h.split(C);i=a[q++];){s=v?s:!j.hasClass(i);j[s?"addClass":"removeClass"](i)}else if(o==="undefined"||o==="boolean"){this.className&&b.data(this,"__className__",this.className);this.className=this.className||h===false?"":b.data(this,"__className__")||""}})},hasClass:function(h){h=" "+h+" ";for(var m=0,o=this.length;m<o;m++)if((" "+this[m].className+" ").replace(n," ").indexOf(h)>-1)return true;return false},val:function(h){if(!arguments.length){var m=this[0];if(m){if(b.nodeName(m,"option")){var o=
m.attributes.value;return!o||o.specified?m.value:m.text}if(b.nodeName(m,"select")){var v=m.selectedIndex;o=[];var i=m.options;m=m.type==="select-one";if(v<0)return null;var q=m?v:0;for(v=m?v+1:i.length;q<v;q++){var j=i[q];if(j.selected&&(b.support.optDisabled?!j.disabled:j.getAttribute("disabled")===null)&&(!j.parentNode.disabled||!b.nodeName(j.parentNode,"optgroup"))){h=b(j).val();if(m)return h;o.push(h)}}return o}if(e.test(m.type)&&!b.support.checkOn)return m.getAttribute("value")===null?"on":m.value;
return(m.value||"").replace(D,"")}return E}var s=b.isFunction(h);return this.each(function(a){var c=b(this),d=h;if(this.nodeType===1){if(s)d=h.call(this,a,c.val());if(d==null)d="";else if(typeof d==="number")d+="";else if(b.isArray(d))d=b.map(d,function(k){return k==null?"":k+""});if(b.isArray(d)&&e.test(this.type))this.checked=b.inArray(c.val(),d)>=0;else if(b.nodeName(this,"select")){var g=b.makeArray(d);b("option",this).each(function(){this.selected=b.inArray(b(this).val(),g)>=0});if(!g.length)this.selectedIndex=
-1}else this.value=d}})}});b.extend({attrFn:{val:true,css:true,html:true,text:true,data:true,width:true,height:true,offset:true},attr:function(h,m,o,v){if(!h||h.nodeType===3||h.nodeType===8)return E;if(v&&m in b.attrFn)return b(h)[m](o);v=h.nodeType!==1||!b.isXMLDoc(h);var i=o!==E;m=v&&b.props[m]||m;var q=l.test(m);if((m in h||h[m]!==E)&&v&&!q){if(i){m==="type"&&r.test(h.nodeName)&&h.parentNode&&b.error("type property can't be changed");if(o===null)h.nodeType===1&&h.removeAttribute(m);else h[m]=o}if(b.nodeName(h,
"form")&&h.getAttributeNode(m))return h.getAttributeNode(m).nodeValue;if(m==="tabIndex")return(m=h.getAttributeNode("tabIndex"))&&m.specified?m.value:u.test(h.nodeName)||t.test(h.nodeName)&&h.href?0:E;return h[m]}if(!b.support.style&&v&&m==="style"){if(i)h.style.cssText=""+o;return h.style.cssText}i&&h.setAttribute(m,""+o);if(!h.attributes[m]&&h.hasAttribute&&!h.hasAttribute(m))return E;h=!b.support.hrefNormalized&&v&&q?h.getAttribute(m,2):h.getAttribute(m);return h===null?E:h}})})(K);(function(){function b(a,
c,d,g,k,p){k=0;for(var x=g.length;k<x;k++){var A=g[k];if(A){var G=false;for(A=A[a];A;){if(A.sizcache===d){G=g[A.sizset];break}if(A.nodeType===1&&!p){A.sizcache=d;A.sizset=k}if(A.nodeName.toLowerCase()===c){G=A;break}A=A[a]}g[k]=G}}}function n(a,c,d,g,k,p){k=0;for(var x=g.length;k<x;k++){var A=g[k];if(A){var G=false;for(A=A[a];A;){if(A.sizcache===d){G=g[A.sizset];break}if(A.nodeType===1){if(!p){A.sizcache=d;A.sizset=k}if(typeof c!=="string"){if(A===c){G=true;break}}else if(t.filter(c,[A]).length>0){G=
A;break}}A=A[a]}g[k]=G}}}var C=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^\[\]]*\]|['"][^'"]*['"]|[^\[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,D=0,l=Object.prototype.toString,r=false,u=true;[0,0].sort(function(){u=false;return 0});var t=function(a,c,d,g){d=d||[];var k=c=c||y;if(c.nodeType!==1&&c.nodeType!==9)return[];if(!a||typeof a!=="string")return d;var p,x,A,G,M,N=true,O=t.isXML(c),F=[],Q=a;do{C.exec("");if(p=C.exec(Q)){Q=p[3];F.push(p[1]);if(p[2]){G=p[3];break}}}while(p);
if(F.length>1&&h.exec(a))if(F.length===2&&e.relative[F[0]])x=s(F[0]+F[1],c);else for(x=e.relative[F[0]]?[c]:t(F.shift(),c);F.length;){a=F.shift();if(e.relative[a])a+=F.shift();x=s(a,x)}else{if(!g&&F.length>1&&c.nodeType===9&&!O&&e.match.ID.test(F[0])&&!e.match.ID.test(F[F.length-1])){p=t.find(F.shift(),c,O);c=p.expr?t.filter(p.expr,p.set)[0]:p.set[0]}if(c){p=g?{expr:F.pop(),set:v(g)}:t.find(F.pop(),F.length===1&&(F[0]==="~"||F[0]==="+")&&c.parentNode?c.parentNode:c,O);x=p.expr?t.filter(p.expr,p.set):
p.set;if(F.length>0)A=v(x);else N=false;for(;F.length;){p=M=F.pop();if(e.relative[M])p=F.pop();else M="";if(p==null)p=c;e.relative[M](A,p,O)}}else A=[]}A||(A=x);A||t.error(M||a);if(l.call(A)==="[object Array]")if(N)if(c&&c.nodeType===1)for(a=0;A[a]!=null;a++){if(A[a]&&(A[a]===true||A[a].nodeType===1&&t.contains(c,A[a])))d.push(x[a])}else for(a=0;A[a]!=null;a++)A[a]&&A[a].nodeType===1&&d.push(x[a]);else d.push.apply(d,A);else v(A,d);if(G){t(G,k,d,g);t.uniqueSort(d)}return d};t.uniqueSort=function(a){if(q){r=
u;a.sort(q);if(r)for(var c=1;c<a.length;c++)a[c]===a[c-1]&&a.splice(c--,1)}return a};t.matches=function(a,c){return t(a,null,null,c)};t.matchesSelector=function(a,c){return t(c,null,null,[a]).length>0};t.find=function(a,c,d){var g;if(!a)return[];for(var k=0,p=e.order.length;k<p;k++){var x,A=e.order[k];if(x=e.leftMatch[A].exec(a)){var G=x[1];x.splice(1,1);if(G.substr(G.length-1)!=="\\"){x[1]=(x[1]||"").replace(/\\/g,"");g=e.find[A](x,c,d);if(g!=null){a=a.replace(e.match[A],"");break}}}}g||(g=c.getElementsByTagName("*"));
return{set:g,expr:a}};t.filter=function(a,c,d,g){for(var k,p,x=a,A=[],G=c,M=c&&c[0]&&t.isXML(c[0]);a&&c.length;){for(var N in e.filter)if((k=e.leftMatch[N].exec(a))!=null&&k[2]){var O,F,Q=e.filter[N];F=k[1];p=false;k.splice(1,1);if(F.substr(F.length-1)!=="\\"){if(G===A)A=[];if(e.preFilter[N])if(k=e.preFilter[N](k,G,d,A,g,M)){if(k===true)continue}else p=O=true;if(k)for(var f=0;(F=G[f])!=null;f++)if(F){O=Q(F,k,f,G);var w=g^!!O;if(d&&O!=null)if(w)p=true;else G[f]=false;else if(w){A.push(F);p=true}}if(O!==
E){d||(G=A);a=a.replace(e.match[N],"");if(!p)return[];break}}}if(a===x)if(p==null)t.error(a);else break;x=a}return G};t.error=function(a){throw"Syntax error, unrecognized expression: "+a;};var e=t.selectors={order:["ID","NAME","TAG"],match:{ID:/#((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,CLASS:/\.((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u00c0-\uFFFF\-]|\\.)+)['"]*\]/,ATTR:/\[\s*((?:[\w\u00c0-\uFFFF\-]|\\.)+)\s*(?:(\S?=)\s*(['"]*)(.*?)\3|)\s*\]/,TAG:/^((?:[\w\u00c0-\uFFFF\*\-]|\\.)+)/,CHILD:/:(only|nth|last|first)-child(?:\((even|odd|[\dn+\-]*)\))?/,
POS:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^\-]|$)/,PSEUDO:/:((?:[\w\u00c0-\uFFFF\-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},leftMatch:{},attrMap:{"class":"className","for":"htmlFor"},attrHandle:{href:function(a){return a.getAttribute("href")}},relative:{"+":function(a,c){var d=typeof c==="string",g=d&&!/\W/.test(c);d=d&&!g;if(g)c=c.toLowerCase();g=0;for(var k=a.length,p;g<k;g++)if(p=a[g]){for(;(p=p.previousSibling)&&p.nodeType!==1;);a[g]=d||p&&p.nodeName.toLowerCase()===
c?p||false:p===c}d&&t.filter(c,a,true)},">":function(a,c){var d,g=typeof c==="string",k=0,p=a.length;if(g&&!/\W/.test(c))for(c=c.toLowerCase();k<p;k++){if(d=a[k]){d=d.parentNode;a[k]=d.nodeName.toLowerCase()===c?d:false}}else{for(;k<p;k++)if(d=a[k])a[k]=g?d.parentNode:d.parentNode===c;g&&t.filter(c,a,true)}},"":function(a,c,d){var g,k=D++,p=n;if(typeof c==="string"&&!/\W/.test(c)){g=c=c.toLowerCase();p=b}p("parentNode",c,k,a,g,d)},"~":function(a,c,d){var g,k=D++,p=n;if(typeof c==="string"&&!/\W/.test(c)){g=
c=c.toLowerCase();p=b}p("previousSibling",c,k,a,g,d)}},find:{ID:function(a,c,d){if(typeof c.getElementById!=="undefined"&&!d)return(a=c.getElementById(a[1]))&&a.parentNode?[a]:[]},NAME:function(a,c){if(typeof c.getElementsByName!=="undefined"){for(var d=[],g=c.getElementsByName(a[1]),k=0,p=g.length;k<p;k++)g[k].getAttribute("name")===a[1]&&d.push(g[k]);return d.length===0?null:d}},TAG:function(a,c){return c.getElementsByTagName(a[1])}},preFilter:{CLASS:function(a,c,d,g,k,p){a=" "+a[1].replace(/\\/g,
"")+" ";if(p)return a;p=0;for(var x;(x=c[p])!=null;p++)if(x)if(k^(x.className&&(" "+x.className+" ").replace(/[\t\n]/g," ").indexOf(a)>=0))d||g.push(x);else if(d)c[p]=false;return false},ID:function(a){return a[1].replace(/\\/g,"")},TAG:function(a){return a[1].toLowerCase()},CHILD:function(a){if(a[1]==="nth"){var c=/(-?)(\d*)n((?:\+|-)?\d*)/.exec(a[2]==="even"&&"2n"||a[2]==="odd"&&"2n+1"||!/\D/.test(a[2])&&"0n+"+a[2]||a[2]);a[2]=c[1]+(c[2]||1)-0;a[3]=c[3]-0}a[0]=D++;return a},ATTR:function(a,c,d,
g,k,p){c=a[1].replace(/\\/g,"");if(!p&&e.attrMap[c])a[1]=e.attrMap[c];if(a[2]==="~=")a[4]=" "+a[4]+" ";return a},PSEUDO:function(a,c,d,g,k){if(a[1]==="not")if((C.exec(a[3])||"").length>1||/^\w/.test(a[3]))a[3]=t(a[3],null,null,c);else{a=t.filter(a[3],c,d,true^k);d||g.push.apply(g,a);return false}else if(e.match.POS.test(a[0])||e.match.CHILD.test(a[0]))return true;return a},POS:function(a){a.unshift(true);return a}},filters:{enabled:function(a){return a.disabled===false&&a.type!=="hidden"},disabled:function(a){return a.disabled===
true},checked:function(a){return a.checked===true},selected:function(a){return a.selected===true},parent:function(a){return!!a.firstChild},empty:function(a){return!a.firstChild},has:function(a,c,d){return!!t(d[3],a).length},header:function(a){return/h\d/i.test(a.nodeName)},text:function(a){return"text"===a.type},radio:function(a){return"radio"===a.type},checkbox:function(a){return"checkbox"===a.type},file:function(a){return"file"===a.type},password:function(a){return"password"===a.type},submit:function(a){return"submit"===
a.type},image:function(a){return"image"===a.type},reset:function(a){return"reset"===a.type},button:function(a){return"button"===a.type||a.nodeName.toLowerCase()==="button"},input:function(a){return/input|select|textarea|button/i.test(a.nodeName)}},setFilters:{first:function(a,c){return c===0},last:function(a,c,d,g){return c===g.length-1},even:function(a,c){return c%2===0},odd:function(a,c){return c%2===1},lt:function(a,c,d){return c<d[3]-0},gt:function(a,c,d){return c>d[3]-0},nth:function(a,c,d){return d[3]-
0===c},eq:function(a,c,d){return d[3]-0===c}},filter:{PSEUDO:function(a,c,d,g){var k=c[1],p=e.filters[k];if(p)return p(a,d,c,g);else if(k==="contains")return(a.textContent||a.innerText||t.getText([a])||"").indexOf(c[3])>=0;else if(k==="not"){c=c[3];d=0;for(g=c.length;d<g;d++)if(c[d]===a)return false;return true}else t.error("Syntax error, unrecognized expression: "+k)},CHILD:function(a,c){var d=c[1],g=a;switch(d){case "only":case "first":for(;g=g.previousSibling;)if(g.nodeType===1)return false;if(d===
"first")return true;g=a;case "last":for(;g=g.nextSibling;)if(g.nodeType===1)return false;return true;case "nth":d=c[2];var k=c[3];if(d===1&&k===0)return true;var p=c[0],x=a.parentNode;if(x&&(x.sizcache!==p||!a.nodeIndex)){var A=0;for(g=x.firstChild;g;g=g.nextSibling)if(g.nodeType===1)g.nodeIndex=++A;x.sizcache=p}g=a.nodeIndex-k;return d===0?g===0:g%d===0&&g/d>=0}},ID:function(a,c){return a.nodeType===1&&a.getAttribute("id")===c},TAG:function(a,c){return c==="*"&&a.nodeType===1||a.nodeName.toLowerCase()===
c},CLASS:function(a,c){return(" "+(a.className||a.getAttribute("class"))+" ").indexOf(c)>-1},ATTR:function(a,c){var d=c[1];d=e.attrHandle[d]?e.attrHandle[d](a):a[d]!=null?a[d]:a.getAttribute(d);var g=d+"",k=c[2],p=c[4];return d==null?k==="!=":k==="="?g===p:k==="*="?g.indexOf(p)>=0:k==="~="?(" "+g+" ").indexOf(p)>=0:!p?g&&d!==false:k==="!="?g!==p:k==="^="?g.indexOf(p)===0:k==="$="?g.substr(g.length-p.length)===p:k==="|="?g===p||g.substr(0,p.length+1)===p+"-":false},POS:function(a,c,d,g){var k=e.setFilters[c[2]];
if(k)return k(a,d,c,g)}}},h=e.match.POS,m=function(a,c){return"\\"+(c-0+1)},o;for(o in e.match){e.match[o]=RegExp(e.match[o].source+/(?![^\[]*\])(?![^\(]*\))/.source);e.leftMatch[o]=RegExp(/(^(?:.|\r|\n)*?)/.source+e.match[o].source.replace(/\\(\d+)/g,m))}var v=function(a,c){a=Array.prototype.slice.call(a,0);if(c){c.push.apply(c,a);return c}return a};try{Array.prototype.slice.call(y.documentElement.childNodes,0)}catch(i){v=function(a,c){var d=0,g=c||[];if(l.call(a)==="[object Array]")Array.prototype.push.apply(g,
a);else if(typeof a.length==="number")for(var k=a.length;d<k;d++)g.push(a[d]);else for(;a[d];d++)g.push(a[d]);return g}}var q,j;if(y.documentElement.compareDocumentPosition)q=function(a,c){if(a===c){r=true;return 0}if(!a.compareDocumentPosition||!c.compareDocumentPosition)return a.compareDocumentPosition?-1:1;return a.compareDocumentPosition(c)&4?-1:1};else{q=function(a,c){var d,g,k=[],p=[];d=a.parentNode;g=c.parentNode;var x=d;if(a===c){r=true;return 0}else if(d===g)return j(a,c);else if(d){if(!g)return 1}else return-1;
for(;x;){k.unshift(x);x=x.parentNode}for(x=g;x;){p.unshift(x);x=x.parentNode}d=k.length;g=p.length;for(x=0;x<d&&x<g;x++)if(k[x]!==p[x])return j(k[x],p[x]);return x===d?j(a,p[x],-1):j(k[x],c,1)};j=function(a,c,d){if(a===c)return d;for(a=a.nextSibling;a;){if(a===c)return-1;a=a.nextSibling}return 1}}t.getText=function(a){for(var c="",d,g=0;a[g];g++){d=a[g];if(d.nodeType===3||d.nodeType===4)c+=d.nodeValue;else if(d.nodeType!==8)c+=t.getText(d.childNodes)}return c};(function(){var a=y.createElement("div"),
c="script"+(new Date).getTime(),d=y.documentElement;a.innerHTML="<a name='"+c+"'/>";d.insertBefore(a,d.firstChild);if(y.getElementById(c)){e.find.ID=function(g,k,p){if(typeof k.getElementById!=="undefined"&&!p)return(k=k.getElementById(g[1]))?k.id===g[1]||typeof k.getAttributeNode!=="undefined"&&k.getAttributeNode("id").nodeValue===g[1]?[k]:E:[]};e.filter.ID=function(g,k){var p=typeof g.getAttributeNode!=="undefined"&&g.getAttributeNode("id");return g.nodeType===1&&p&&p.nodeValue===k}}d.removeChild(a);
d=a=null})();(function(){var a=y.createElement("div");a.appendChild(y.createComment(""));if(a.getElementsByTagName("*").length>0)e.find.TAG=function(c,d){var g=d.getElementsByTagName(c[1]);if(c[1]==="*"){for(var k=[],p=0;g[p];p++)g[p].nodeType===1&&k.push(g[p]);g=k}return g};a.innerHTML="<a href='#'></a>";if(a.firstChild&&typeof a.firstChild.getAttribute!=="undefined"&&a.firstChild.getAttribute("href")!=="#")e.attrHandle.href=function(c){return c.getAttribute("href",2)};a=null})();y.querySelectorAll&&
function(){var a=t,c=y.createElement("div");c.innerHTML="<p class='TEST'></p>";if(!(c.querySelectorAll&&c.querySelectorAll(".TEST").length===0)){t=function(g,k,p,x){k=k||y;g=g.replace(/\=\s*([^'"\]]*)\s*\]/g,"='$1']");if(!x&&!t.isXML(k))if(k.nodeType===9)try{return v(k.querySelectorAll(g),p)}catch(A){}else if(k.nodeType===1&&k.nodeName.toLowerCase()!=="object"){var G=k.getAttribute("id"),M=G||"__sizzle__";G||k.setAttribute("id",M);try{return v(k.querySelectorAll("#"+M+" "+g),p)}catch(N){}finally{G||
k.removeAttribute("id")}}return a(g,k,p,x)};for(var d in a)t[d]=a[d];c=null}}();(function(){var a=y.documentElement,c=a.matchesSelector||a.mozMatchesSelector||a.webkitMatchesSelector||a.msMatchesSelector,d=false;try{c.call(y.documentElement,"[test!='']:sizzle")}catch(g){d=true}if(c)t.matchesSelector=function(k,p){p=p.replace(/\=\s*([^'"\]]*)\s*\]/g,"='$1']");if(!t.isXML(k))try{if(d||!e.match.PSEUDO.test(p)&&!/!=/.test(p))return c.call(k,p)}catch(x){}return t(p,null,null,[k]).length>0}})();(function(){var a=
y.createElement("div");a.innerHTML="<div class='test e'></div><div class='test'></div>";if(!(!a.getElementsByClassName||a.getElementsByClassName("e").length===0)){a.lastChild.className="e";if(a.getElementsByClassName("e").length!==1){e.order.splice(1,0,"CLASS");e.find.CLASS=function(c,d,g){if(typeof d.getElementsByClassName!=="undefined"&&!g)return d.getElementsByClassName(c[1])};a=null}}})();t.contains=y.documentElement.contains?function(a,c){return a!==c&&(a.contains?a.contains(c):true)}:y.documentElement.compareDocumentPosition?
function(a,c){return!!(a.compareDocumentPosition(c)&16)}:function(){return false};t.isXML=function(a){return(a=(a?a.ownerDocument||a:0).documentElement)?a.nodeName!=="HTML":false};var s=function(a,c){for(var d,g=[],k="",p=c.nodeType?[c]:c;d=e.match.PSEUDO.exec(a);){k+=d[0];a=a.replace(e.match.PSEUDO,"")}a=e.relative[a]?a+"*":a;d=0;for(var x=p.length;d<x;d++)t(a,p[d],g);return t.filter(k,g)};K.find=t;K.expr=t.selectors;K.expr[":"]=K.expr.filters;K.unique=t.uniqueSort;K.text=t.getText;K.isXMLDoc=t.isXML;
K.contains=t.contains})();(function(b){function n(e,h,m){if(b.isFunction(h))return b.grep(e,function(v,i){return!!h.call(v,i,v)===m});else if(h.nodeType)return b.grep(e,function(v){return v===h===m});else if(typeof h==="string"){var o=b.grep(e,function(v){return v.nodeType===1});if(r.test(h))return b.filter(h,o,!m);else h=b.filter(h,o)}return b.grep(e,function(v){return b.inArray(v,h)>=0===m})}var C=/Until$/,D=/^(?:parents|prevUntil|prevAll)/,l=/,/,r=/^.[^:#\[\.,]*$/,u=Array.prototype.slice,t=b.expr.match.POS;
b.fn.extend({find:function(e){for(var h=this.pushStack("","find",e),m=0,o=0,v=this.length;o<v;o++){m=h.length;b.find(e,this[o],h);if(o>0)for(var i=m;i<h.length;i++)for(var q=0;q<m;q++)if(h[q]===h[i]){h.splice(i--,1);break}}return h},has:function(e){var h=b(e);return this.filter(function(){for(var m=0,o=h.length;m<o;m++)if(b.contains(this,h[m]))return true})},not:function(e){return this.pushStack(n(this,e,false),"not",e)},filter:function(e){return this.pushStack(n(this,e,true),"filter",e)},is:function(e){return!!e&&
b.filter(e,this).length>0},closest:function(e,h){var m=[],o,v,i=this[0];if(b.isArray(e)){var q,j={},s=1;if(i&&e.length){o=0;for(v=e.length;o<v;o++){q=e[o];j[q]||(j[q]=b.expr.match.POS.test(q)?b(q,h||this.context):q)}for(;i&&i.ownerDocument&&i!==h;){for(q in j){o=j[q];if(o.jquery?o.index(i)>-1:b(i).is(o))m.push({selector:q,elem:i,level:s})}i=i.parentNode;s++}}return m}q=t.test(e)?b(e,h||this.context):null;o=0;for(v=this.length;o<v;o++)for(i=this[o];i;)if(q?q.index(i)>-1:b.find.matchesSelector(i,e)){m.push(i);
break}else{i=i.parentNode;if(!i||!i.ownerDocument||i===h)break}m=m.length>1?b.unique(m):m;return this.pushStack(m,"closest",e)},index:function(e){if(!e||typeof e==="string")return b.inArray(this[0],e?b(e):this.parent().children());return b.inArray(e.jquery?e[0]:e,this)},add:function(e,h){var m=typeof e==="string"?b(e,h||this.context):b.makeArray(e),o=b.merge(this.get(),m);return this.pushStack(!m[0]||!m[0].parentNode||m[0].parentNode.nodeType===11||!o[0]||!o[0].parentNode||o[0].parentNode.nodeType===
11?o:b.unique(o))},andSelf:function(){return this.add(this.prevObject)}});b.each({parent:function(e){return(e=e.parentNode)&&e.nodeType!==11?e:null},parents:function(e){return b.dir(e,"parentNode")},parentsUntil:function(e,h,m){return b.dir(e,"parentNode",m)},next:function(e){return b.nth(e,2,"nextSibling")},prev:function(e){return b.nth(e,2,"previousSibling")},nextAll:function(e){return b.dir(e,"nextSibling")},prevAll:function(e){return b.dir(e,"previousSibling")},nextUntil:function(e,h,m){return b.dir(e,
"nextSibling",m)},prevUntil:function(e,h,m){return b.dir(e,"previousSibling",m)},siblings:function(e){return b.sibling(e.parentNode.firstChild,e)},children:function(e){return b.sibling(e.firstChild)},contents:function(e){return b.nodeName(e,"iframe")?e.contentDocument||e.contentWindow.document:b.makeArray(e.childNodes)}},function(e,h){b.fn[e]=function(m,o){var v=b.map(this,h,m);C.test(e)||(o=m);if(o&&typeof o==="string")v=b.filter(o,v);v=this.length>1?b.unique(v):v;if((this.length>1||l.test(o))&&
D.test(e))v=v.reverse();return this.pushStack(v,e,u.call(arguments).join(","))}});b.extend({filter:function(e,h,m){if(m)e=":not("+e+")";return h.length===1?b.find.matchesSelector(h[0],e)?[h[0]]:[]:b.find.matches(e,h)},dir:function(e,h,m){var o=[];for(e=e[h];e&&e.nodeType!==9&&(m===E||e.nodeType!==1||!b(e).is(m));){e.nodeType===1&&o.push(e);e=e[h]}return o},nth:function(e,h,m){h=h||1;for(var o=0;e;e=e[m])if(e.nodeType===1&&++o===h)break;return e},sibling:function(e,h){for(var m=[];e;e=e.nextSibling)e.nodeType===
1&&e!==h&&m.push(e);return m}})})(K);(function(b){function n(i,q){var j=0;q.each(function(){if(this.nodeName===(i[j]&&i[j].nodeName)){var s=b.data(i[j++]),a=b.data(this,s);if(s=s&&s.events){delete a.handle;a.events={};for(var c in s)for(var d in s[c])b.event.add(this,c,s[c][d],s[c][d].data)}}})}function C(i,q){q.src?b.ajax({url:q.src,async:false,dataType:"script"}):b.globalEval(q.text||q.textContent||q.innerHTML||"");q.parentNode&&q.parentNode.removeChild(q)}var D=/ jQuery\d+="(?:\d+|null)"/g,l=/^\s+/,
r=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,u=/<([\w:]+)/,t=/<tbody/i,e=/<|&#?\w+;/,h=/<(?:script|object|embed|option|style)/i,m=/checked\s*(?:[^=]|=\s*.checked.)/i,o=/\=([^="'>\s]+\/)>/g,v={option:[1,"<select multiple='multiple'>","</select>"],legend:[1,"<fieldset>","</fieldset>"],thead:[1,"<table>","</table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],col:[2,"<table><tbody></tbody><colgroup>","</colgroup></table>"],
area:[1,"<map>","</map>"],_default:[0,"",""]};v.optgroup=v.option;v.tbody=v.tfoot=v.colgroup=v.caption=v.thead;v.th=v.td;if(!b.support.htmlSerialize)v._default=[1,"div<div>","</div>"];b.fn.extend({text:function(i){if(b.isFunction(i))return this.each(function(q){var j=b(this);j.text(i.call(this,q,j.text()))});if(typeof i!=="object"&&i!==E)return this.empty().append((this[0]&&this[0].ownerDocument||y).createTextNode(i));return b.text(this)},wrapAll:function(i){if(b.isFunction(i))return this.each(function(j){b(this).wrapAll(i.call(this,
j))});if(this[0]){var q=b(i,this[0].ownerDocument).eq(0).clone(true);this[0].parentNode&&q.insertBefore(this[0]);q.map(function(){for(var j=this;j.firstChild&&j.firstChild.nodeType===1;)j=j.firstChild;return j}).append(this)}return this},wrapInner:function(i){if(b.isFunction(i))return this.each(function(q){b(this).wrapInner(i.call(this,q))});return this.each(function(){var q=b(this),j=q.contents();j.length?j.wrapAll(i):q.append(i)})},wrap:function(i){return this.each(function(){b(this).wrapAll(i)})},
unwrap:function(){return this.parent().each(function(){b.nodeName(this,"body")||b(this).replaceWith(this.childNodes)}).end()},append:function(){return this.domManip(arguments,true,function(i){this.nodeType===1&&this.appendChild(i)})},prepend:function(){return this.domManip(arguments,true,function(i){this.nodeType===1&&this.insertBefore(i,this.firstChild)})},before:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,false,function(q){this.parentNode.insertBefore(q,this)});else if(arguments.length){var i=
b(arguments[0]);i.push.apply(i,this.toArray());return this.pushStack(i,"before",arguments)}},after:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,false,function(q){this.parentNode.insertBefore(q,this.nextSibling)});else if(arguments.length){var i=this.pushStack(this,"after",arguments);i.push.apply(i,b(arguments[0]).toArray());return i}},remove:function(i,q){for(var j=0,s;(s=this[j])!=null;j++)if(!i||b.filter(i,[s]).length){if(!q&&s.nodeType===1){b.cleanData(s.getElementsByTagName("*"));
b.cleanData([s])}s.parentNode&&s.parentNode.removeChild(s)}return this},empty:function(){for(var i=0,q;(q=this[i])!=null;i++)for(q.nodeType===1&&b.cleanData(q.getElementsByTagName("*"));q.firstChild;)q.removeChild(q.firstChild);return this},clone:function(i){var q=this.map(function(){if(!b.support.noCloneEvent&&!b.isXMLDoc(this)){var j=this.outerHTML,s=this.ownerDocument;if(!j){j=s.createElement("div");j.appendChild(this.cloneNode(true));j=j.innerHTML}return b.clean([j.replace(D,"").replace(o,'="$1">').replace(l,
"")],s)[0]}else return this.cloneNode(true)});if(i===true){n(this,q);n(this.find("*"),q.find("*"))}return q},html:function(i){if(i===E)return this[0]&&this[0].nodeType===1?this[0].innerHTML.replace(D,""):null;else if(typeof i==="string"&&!h.test(i)&&(b.support.leadingWhitespace||!l.test(i))&&!v[(u.exec(i)||["",""])[1].toLowerCase()]){i=i.replace(r,"<$1></$2>");try{for(var q=0,j=this.length;q<j;q++)if(this[q].nodeType===1){b.cleanData(this[q].getElementsByTagName("*"));this[q].innerHTML=i}}catch(s){this.empty().append(i)}}else b.isFunction(i)?
this.each(function(a){var c=b(this);c.html(i.call(this,a,c.html()))}):this.empty().append(i);return this},replaceWith:function(i){if(this[0]&&this[0].parentNode){if(b.isFunction(i))return this.each(function(q){var j=b(this),s=j.html();j.replaceWith(i.call(this,q,s))});if(typeof i!=="string")i=b(i).detach();return this.each(function(){var q=this.nextSibling,j=this.parentNode;b(this).remove();q?b(q).before(i):b(j).append(i)})}else return this.pushStack(b(b.isFunction(i)?i():i),"replaceWith",i)},detach:function(i){return this.remove(i,
true)},domManip:function(i,q,j){var s,a,c,d=i[0],g=[];if(!b.support.checkClone&&arguments.length===3&&typeof d==="string"&&m.test(d))return this.each(function(){b(this).domManip(i,q,j,true)});if(b.isFunction(d))return this.each(function(p){var x=b(this);i[0]=d.call(this,p,q?x.html():E);x.domManip(i,q,j)});if(this[0]){s=d&&d.parentNode;s=b.support.parentNode&&s&&s.nodeType===11&&s.childNodes.length===this.length?{fragment:s}:b.buildFragment(i,this,g);c=s.fragment;if(a=c.childNodes.length===1?c=c.firstChild:
c.firstChild){q=q&&b.nodeName(a,"tr");a=0;for(var k=this.length;a<k;a++)j.call(q?b.nodeName(this[a],"table")?this[a].getElementsByTagName("tbody")[0]||this[a].appendChild(this[a].ownerDocument.createElement("tbody")):this[a]:this[a],a>0||s.cacheable||this.length>1?c.cloneNode(true):c)}g.length&&b.each(g,C)}return this}});b.buildFragment=function(i,q,j){var s,a,c;q=q&&q[0]?q[0].ownerDocument||q[0]:y;if(i.length===1&&typeof i[0]==="string"&&i[0].length<512&&q===y&&!h.test(i[0])&&(b.support.checkClone||
!m.test(i[0]))){a=true;if(c=b.fragments[i[0]])if(c!==1)s=c}if(!s){s=q.createDocumentFragment();b.clean(i,q,s,j)}if(a)b.fragments[i[0]]=c?s:1;return{fragment:s,cacheable:a}};b.fragments={};b.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(i,q){b.fn[i]=function(j){var s=[];j=b(j);var a=this.length===1&&this[0].parentNode;if(a&&a.nodeType===11&&a.childNodes.length===1&&j.length===1){j[q](this[0]);return this}else{a=0;for(var c=
j.length;a<c;a++){var d=(a>0?this.clone(true):this).get();b(j[a])[q](d);s=s.concat(d)}return this.pushStack(s,i,j.selector)}}});b.extend({clean:function(i,q,j,s){q=q||y;if(typeof q.createElement==="undefined")q=q.ownerDocument||q[0]&&q[0].ownerDocument||y;for(var a=[],c=0,d;(d=i[c])!=null;c++){if(typeof d==="number")d+="";if(d){if(typeof d==="string"&&!e.test(d))d=q.createTextNode(d);else if(typeof d==="string"){d=d.replace(r,"<$1></$2>");var g=(u.exec(d)||["",""])[1].toLowerCase(),k=v[g]||v._default,
p=k[0],x=q.createElement("div");for(x.innerHTML=k[1]+d+k[2];p--;)x=x.lastChild;if(!b.support.tbody){p=t.test(d);g=g==="table"&&!p?x.firstChild&&x.firstChild.childNodes:k[1]==="<table>"&&!p?x.childNodes:[];for(k=g.length-1;k>=0;--k)b.nodeName(g[k],"tbody")&&!g[k].childNodes.length&&g[k].parentNode.removeChild(g[k])}!b.support.leadingWhitespace&&l.test(d)&&x.insertBefore(q.createTextNode(l.exec(d)[0]),x.firstChild);d=x.childNodes}if(d.nodeType)a.push(d);else a=b.merge(a,d)}}if(j)for(c=0;a[c];c++)if(s&&
b.nodeName(a[c],"script")&&(!a[c].type||a[c].type.toLowerCase()==="text/javascript"))s.push(a[c].parentNode?a[c].parentNode.removeChild(a[c]):a[c]);else{a[c].nodeType===1&&a.splice.apply(a,[c+1,0].concat(b.makeArray(a[c].getElementsByTagName("script"))));j.appendChild(a[c])}return a},cleanData:function(i){for(var q,j=b.cache,s=b.support.deleteExpando,a=0,c;(c=i[a])!=null;a++)if(!(c.nodeName&&b.noData[c.nodeName.toLowerCase()]))if(q=c[b.expando]){if(s)delete c[b.expando];else c.removeAttribute&&c.removeAttribute(b.expando);
delete j[q]}}})})(K);(function(b){function n(j,s,a){var c=s==="width"?j.offsetWidth:j.offsetHeight;if(a==="border")return c;b.each(s==="width"?h:m,function(){a||(c-=parseFloat(b.css(j,"padding"+this))||0);if(a==="margin")c+=parseFloat(b.css(j,"margin"+this))||0;else c-=parseFloat(b.css(j,"border"+this+"Width"))||0});return c}var C=/alpha\([^)]*\)/i,D=/opacity=([^)]*)/,l=/-([a-z])/ig,r=/([A-Z])/g,u=/^-?\d+(?:px)?$/i,t=/^-?\d/,e={position:"absolute",visibility:"hidden",display:"block"},h=["Left","Right"],
m=["Top","Bottom"],o,v,i,q=function(j,s){return s.toUpperCase()};b.fn.css=function(j,s){if(arguments.length===2&&s===E)return this;return b.access(this,j,s,true,function(a,c,d){return d!==E?b.style(a,c,d):b.css(a,c)})};b.extend({cssHooks:{opacity:{get:function(j,s){if(s){var a=o(j,"opacity","opacity");return a===""?"1":a}else return j.style.opacity}}},cssNumber:{zIndex:true,fontWeight:true,opacity:true,zoom:true,lineHeight:true},cssProps:{"float":b.support.cssFloat?"cssFloat":"styleFloat"},style:function(j,
s,a,c){if(!(!j||j.nodeType===3||j.nodeType===8||!j.style)){var d,g=b.camelCase(s),k=j.style,p=b.cssHooks[g];s=b.cssProps[g]||g;if(a!==E){if(!(typeof a==="number"&&isNaN(a)||a==null)){if(typeof a==="number"&&!b.cssNumber[g])a+="px";if(!p||!("set"in p)||(a=p.set(j,a))!==E)try{k[s]=a}catch(x){}}}else{if(p&&"get"in p&&(d=p.get(j,false,c))!==E)return d;return k[s]}}},css:function(j,s,a){var c,d=b.camelCase(s),g=b.cssHooks[d];s=b.cssProps[d]||d;if(g&&"get"in g&&(c=g.get(j,true,a))!==E)return c;else if(o)return o(j,
s,d)},swap:function(j,s,a){var c={},d;for(d in s){c[d]=j.style[d];j.style[d]=s[d]}a.call(j);for(d in s)j.style[d]=c[d]},camelCase:function(j){return j.replace(l,q)}});b.curCSS=b.css;b.each(["height","width"],function(j,s){b.cssHooks[s]={get:function(a,c,d){var g;if(c){if(a.offsetWidth!==0)g=n(a,s,d);else b.swap(a,e,function(){g=n(a,s,d)});if(g<=0){g=o(a,s,s);if(g==="0px"&&i)g=i(a,s,s);if(g!=null)return g===""||g==="auto"?"0px":g}if(g<0||g==null){g=a.style[s];return g===""||g==="auto"?"0px":g}return typeof g===
"string"?g:g+"px"}},set:function(a,c){if(u.test(c)){c=parseFloat(c);if(c>=0)return c+"px"}else return c}}});if(!b.support.opacity)b.cssHooks.opacity={get:function(j,s){return D.test((s&&j.currentStyle?j.currentStyle.filter:j.style.filter)||"")?parseFloat(RegExp.$1)/100+"":s?"1":""},set:function(j,s){var a=j.style;a.zoom=1;var c=b.isNaN(s)?"":"alpha(opacity="+s*100+")",d=a.filter||"";a.filter=C.test(d)?d.replace(C,c):a.filter+" "+c}};if(y.defaultView&&y.defaultView.getComputedStyle)v=function(j,s,
a){var c;a=a.replace(r,"-$1").toLowerCase();if(!(s=j.ownerDocument.defaultView))return E;if(s=s.getComputedStyle(j,null)){c=s.getPropertyValue(a);if(c===""&&!b.contains(j.ownerDocument.documentElement,j))c=b.style(j,a)}return c};if(y.documentElement.currentStyle)i=function(j,s){var a,c,d=j.currentStyle&&j.currentStyle[s],g=j.style;if(!u.test(d)&&t.test(d)){a=g.left;c=j.runtimeStyle.left;j.runtimeStyle.left=j.currentStyle.left;g.left=s==="fontSize"?"1em":d||0;d=g.pixelLeft+"px";g.left=a;j.runtimeStyle.left=
c}return d===""?"auto":d};o=v||i;if(b.expr&&b.expr.filters){b.expr.filters.hidden=function(j){var s=j.offsetHeight;return j.offsetWidth===0&&s===0||!b.support.reliableHiddenOffsets&&(j.style.display||b.css(j,"display"))==="none"};b.expr.filters.visible=function(j){return!b.expr.filters.hidden(j)}}})(K);(function(b){function n(l){return b.isWindow(l)?l:l.nodeType===9?l.defaultView||l.parentWindow:false}var C=/^t(?:able|d|h)$/i,D=/^(?:body|html)$/i;b.fn.offset="getBoundingClientRect"in y.documentElement?
function(l){var r=this[0],u;if(l)return this.each(function(m){b.offset.setOffset(this,l,m)});if(!r||!r.ownerDocument)return null;if(r===r.ownerDocument.body)return b.offset.bodyOffset(r);try{u=r.getBoundingClientRect()}catch(t){}var e=r.ownerDocument,h=e.documentElement;if(!u||!b.contains(h,r))return u||{top:0,left:0};r=e.body;e=n(e);return{top:u.top+(e.pageYOffset||b.support.boxModel&&h.scrollTop||r.scrollTop)-(h.clientTop||r.clientTop||0),left:u.left+(e.pageXOffset||b.support.boxModel&&h.scrollLeft||
r.scrollLeft)-(h.clientLeft||r.clientLeft||0)}}:function(l){var r=this[0];if(l)return this.each(function(i){b.offset.setOffset(this,l,i)});if(!r||!r.ownerDocument)return null;if(r===r.ownerDocument.body)return b.offset.bodyOffset(r);b.offset.initialize();var u,t=r.offsetParent,e=r.ownerDocument,h=e.documentElement,m=e.body;u=(e=e.defaultView)?e.getComputedStyle(r,null):r.currentStyle;for(var o=r.offsetTop,v=r.offsetLeft;(r=r.parentNode)&&r!==m&&r!==h;){if(b.offset.supportsFixedPosition&&u.position===
"fixed")break;u=e?e.getComputedStyle(r,null):r.currentStyle;o-=r.scrollTop;v-=r.scrollLeft;if(r===t){o+=r.offsetTop;v+=r.offsetLeft;if(b.offset.doesNotAddBorder&&!(b.offset.doesAddBorderForTableAndCells&&C.test(r.nodeName))){o+=parseFloat(u.borderTopWidth)||0;v+=parseFloat(u.borderLeftWidth)||0}t=r.offsetParent}if(b.offset.subtractsBorderForOverflowNotVisible&&u.overflow!=="visible"){o+=parseFloat(u.borderTopWidth)||0;v+=parseFloat(u.borderLeftWidth)||0}u=u}if(u.position==="relative"||u.position===
"static"){o+=m.offsetTop;v+=m.offsetLeft}if(b.offset.supportsFixedPosition&&u.position==="fixed"){o+=Math.max(h.scrollTop,m.scrollTop);v+=Math.max(h.scrollLeft,m.scrollLeft)}return{top:o,left:v}};b.offset={initialize:function(){var l=y.body,r=y.createElement("div"),u,t,e,h=parseFloat(b.css(l,"marginTop"))||0;b.extend(r.style,{position:"absolute",top:0,left:0,margin:0,border:0,width:"1px",height:"1px",visibility:"hidden"});r.innerHTML="<div style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;'><div></div></div><table style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;' cellpadding='0' cellspacing='0'><tr><td></td></tr></table>";
l.insertBefore(r,l.firstChild);u=r.firstChild;t=u.firstChild;e=u.nextSibling.firstChild.firstChild;this.doesNotAddBorder=t.offsetTop!==5;this.doesAddBorderForTableAndCells=e.offsetTop===5;t.style.position="fixed";t.style.top="20px";this.supportsFixedPosition=t.offsetTop===20||t.offsetTop===15;t.style.position=t.style.top="";u.style.overflow="hidden";u.style.position="relative";this.subtractsBorderForOverflowNotVisible=t.offsetTop===-5;this.doesNotIncludeMarginInBodyOffset=l.offsetTop!==h;l.removeChild(r);
b.offset.initialize=b.noop},bodyOffset:function(l){var r=l.offsetTop,u=l.offsetLeft;b.offset.initialize();if(b.offset.doesNotIncludeMarginInBodyOffset){r+=parseFloat(b.css(l,"marginTop"))||0;u+=parseFloat(b.css(l,"marginLeft"))||0}return{top:r,left:u}},setOffset:function(l,r,u){var t=b.css(l,"position");if(t==="static")l.style.position="relative";var e=b(l),h=e.offset(),m=b.css(l,"top"),o=b.css(l,"left"),v=t==="absolute"&&b.inArray("auto",[m,o])>-1;t={};var i={};if(v)i=e.position();m=v?i.top:parseInt(m,
10)||0;o=v?i.left:parseInt(o,10)||0;if(b.isFunction(r))r=r.call(l,u,h);if(r.top!=null)t.top=r.top-h.top+m;if(r.left!=null)t.left=r.left-h.left+o;"using"in r?r.using.call(l,t):e.css(t)}};b.fn.extend({position:function(){if(!this[0])return null;var l=this[0],r=this.offsetParent(),u=this.offset(),t=D.test(r[0].nodeName)?{top:0,left:0}:r.offset();u.top-=parseFloat(b.css(l,"marginTop"))||0;u.left-=parseFloat(b.css(l,"marginLeft"))||0;t.top+=parseFloat(b.css(r[0],"borderTopWidth"))||0;t.left+=parseFloat(b.css(r[0],
"borderLeftWidth"))||0;return{top:u.top-t.top,left:u.left-t.left}},offsetParent:function(){return this.map(function(){for(var l=this.offsetParent||y.body;l&&!D.test(l.nodeName)&&b.css(l,"position")==="static";)l=l.offsetParent;return l})}});b.each(["Left","Top"],function(l,r){var u="scroll"+r;b.fn[u]=function(t){var e=this[0],h;if(!e)return null;if(t!==E)return this.each(function(){if(h=n(this))h.scrollTo(!l?t:b(h).scrollLeft(),l?t:b(h).scrollTop());else this[u]=t});else return(h=n(e))?"pageXOffset"in
h?h[l?"pageYOffset":"pageXOffset"]:b.support.boxModel&&h.document.documentElement[u]||h.document.body[u]:e[u]}})})(K);(function(b){b.each(["Height","Width"],function(n,C){var D=C.toLowerCase();b.fn["inner"+C]=function(){return this[0]?parseFloat(b.css(this[0],D,"padding")):null};b.fn["outer"+C]=function(l){return this[0]?parseFloat(b.css(this[0],D,l?"margin":"border")):null};b.fn[D]=function(l){var r=this[0];if(!r)return l==null?null:this;if(b.isFunction(l))return this.each(function(t){var e=b(this);
e[D](l.call(this,t,e[D]()))});if(b.isWindow(r))return r.document.compatMode==="CSS1Compat"&&r.document.documentElement["client"+C]||r.document.body["client"+C];else if(r.nodeType===9)return Math.max(r.documentElement["client"+C],r.body["scroll"+C],r.documentElement["scroll"+C],r.body["offset"+C],r.documentElement["offset"+C]);else if(l===E){r=b.css(r,D);var u=parseFloat(r);return b.isNaN(u)?r:u}else return this.css(D,typeof l==="string"?l:l+"px")}})})(K)})(window);
