/*!
 * jQuery JavaScript Library v1.4.5pre
 * http://jquery.com/
 *
 * Copyright 2010, John Resig
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * Includes Sizzle.js
 * http://sizzlejs.com/
 * Copyright 2010, The Dojo Foundation
 * Released under the MIT, BSD, and GPL Licenses.
 *
 * Date: Thu Nov 11 19:05:10 2010 -0500
 */
(function(K,H){var v=K.document,L=function(){function c(){if(!o.isReady){try{v.documentElement.doScroll("left")}catch(e){setTimeout(c,1);return}o.ready()}}var o=function(e,p){return new o.fn.init(e,p)},C=K.jQuery,z=K.$,E,B=/^(?:[^<]*(<[\w\W]+>)[^>]*$|#([\w\-]+)$)/,I=/\S/,w=/^\s+/,f=/\s+$/,j=/\W/,m=/\d/,n=/^<(\w+)\s*\/?>(?:<\/\1>)?$/,s=/^[\],:{}\s]*$/,h=/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,k=/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,q=/(?:^|:|,)(?:\s*\[)+/g,t=/(webkit)[ \/]([\w.]+)/,
a=/(opera)(?:.*version)?[ \/]([\w.]+)/,b=/(msie) ([\w.]+)/,d=/(mozilla)(?:.*? rv:([\w.]+))?/,g=navigator.userAgent,i=false,l=[],r,x=Object.prototype.toString,D=Object.prototype.hasOwnProperty,M=Array.prototype.push,N=Array.prototype.slice,O=String.prototype.trim,A=Array.prototype.indexOf,Q={};o.fn=o.prototype={init:function(e,p){var u,y,G;if(!e)return this;if(e.nodeType){this.context=this[0]=e;this.length=1;return this}if(e==="body"&&!p&&v.body){this.context=v;this[0]=v.body;this.selector="body";
this.length=1;return this}if(typeof e==="string")if((u=B.exec(e))&&(u[1]||!p))if(u[1]){G=p?p.ownerDocument||p:v;if(y=n.exec(e))if(o.isPlainObject(p)){e=[v.createElement(y[1])];o.fn.attr.call(e,p,true)}else e=[G.createElement(y[1])];else{y=o.buildFragment([u[1]],[G]);e=(y.cacheable?y.fragment.cloneNode(true):y.fragment).childNodes}return o.merge(this,e)}else{if((y=v.getElementById(u[2]))&&y.parentNode){if(y.id!==u[2])return E.find(e);this.length=1;this[0]=y}this.context=v;this.selector=e;return this}else if(!p&&
!j.test(e)){this.selector=e;this.context=v;e=v.getElementsByTagName(e);return o.merge(this,e)}else return!p||p.jquery?(p||E).find(e):o(p).find(e);else if(o.isFunction(e))return E.ready(e);if(e.selector!==H){this.selector=e.selector;this.context=e.context}return o.makeArray(e,this)},selector:"",jquery:"1.4.5pre",length:0,size:function(){return this.length},toArray:function(){return N.call(this,0)},get:function(e){return e==null?this.toArray():e<0?this.slice(e)[0]:this[e]},pushStack:function(e,p,u){var y=
o();o.isArray(e)?M.apply(y,e):o.merge(y,e);y.prevObject=this;y.context=this.context;if(p==="find")y.selector=this.selector+(this.selector?" ":"")+u;else if(p)y.selector=this.selector+"."+p+"("+u+")";return y},each:function(e,p){return o.each(this,e,p)},ready:function(e){o.bindReady();if(o.isReady)e.call(v,o);else l&&l.push(e);return this},eq:function(e){return e===-1?this.slice(e):this.slice(e,+e+1)},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},slice:function(){return this.pushStack(N.apply(this,
arguments),"slice",N.call(arguments).join(","))},map:function(e){return this.pushStack(o.map(this,function(p,u){return e.call(p,u,p)}))},end:function(){return this.prevObject||o(null)},push:M,sort:[].sort,splice:[].splice};o.fn.init.prototype=o.fn;o.extend=o.fn.extend=function(){var e,p,u,y,G,F=arguments[0]||{},J=1,P=arguments.length,R=false;if(typeof F==="boolean"){R=F;F=arguments[1]||{};J=2}if(typeof F!=="object"&&!o.isFunction(F))F={};if(P===J){F=this;--J}for(;J<P;J++)if((e=arguments[J])!=null)for(p in e){u=
F[p];y=e[p];if(F!==y)if(R&&y&&(o.isPlainObject(y)||(G=o.isArray(y)))){if(G){G=false;u=u&&o.isArray(u)?u:[]}else u=u&&o.isPlainObject(u)?u:{};F[p]=o.extend(R,u,y)}else if(y!==H)F[p]=y}return F};o.extend({noConflict:function(e){K.$=z;if(e)K.jQuery=C;return o},isReady:false,readyWait:1,ready:function(e){e===true&&o.readyWait--;if(!o.readyWait||e!==true&&!o.isReady){if(!v.body)return setTimeout(o.ready,1);o.isReady=true;if(!(e!==true&&--o.readyWait>0))if(l){var p=0,u=l;for(l=null;e=u[p++];)e.call(v,o);
o.fn.trigger&&o(v).trigger("ready").unbind("ready")}}},bindReady:function(){if(!i){i=true;if(v.readyState==="complete")return setTimeout(o.ready,1);if(v.addEventListener){v.addEventListener("DOMContentLoaded",r,false);K.addEventListener("load",o.ready,false)}else if(v.attachEvent){v.attachEvent("onreadystatechange",r);K.attachEvent("onload",o.ready);var e=false;try{e=K.frameElement==null}catch(p){}v.documentElement.doScroll&&e&&c()}}},isFunction:function(e){return o.type(e)==="function"},isArray:Array.isArray||
function(e){return o.type(e)==="array"},isWindow:function(e){return e&&typeof e==="object"&&"setInterval"in e},isNaN:function(e){return e==null||!m.test(e)||isNaN(e)},type:function(e){return e==null?String(e):Q[x.call(e)]||"object"},isPlainObject:function(e){if(!e||o.type(e)!=="object"||e.nodeType||o.isWindow(e))return false;if(e.constructor&&!D.call(e,"constructor")&&!D.call(e.constructor.prototype,"isPrototypeOf"))return false;for(var p in e);return p===H||D.call(e,p)},isEmptyObject:function(e){for(var p in e)return false;
return true},error:function(e){throw e;},parseJSON:function(e){if(typeof e!=="string"||!e)return null;e=o.trim(e);if(s.test(e.replace(h,"@").replace(k,"]").replace(q,"")))return K.JSON&&K.JSON.parse?K.JSON.parse(e):(new Function("return "+e))();else o.error("Invalid JSON: "+e)},noop:function(){},globalEval:function(e){if(e&&I.test(e)){var p=v.getElementsByTagName("head")[0]||v.documentElement,u=v.createElement("script");u.type="text/javascript";if(o.support.scriptEval)u.appendChild(v.createTextNode(e));
else u.text=e;p.insertBefore(u,p.firstChild);p.removeChild(u)}},nodeName:function(e,p){return e.nodeName&&e.nodeName.toUpperCase()===p.toUpperCase()},each:function(e,p,u){var y,G=0,F=e.length,J=F===H||o.isFunction(e);if(u)if(J)for(y in e){if(p.apply(e[y],u)===false)break}else for(;G<F;){if(p.apply(e[G++],u)===false)break}else if(J)for(y in e){if(p.call(e[y],y,e[y])===false)break}else for(u=e[0];G<F&&p.call(u,G,u)!==false;u=e[++G]);return e},trim:O?function(e){return e==null?"":O.call(e)}:function(e){return e==
null?"":e.toString().replace(w,"").replace(f,"")},makeArray:function(e,p){var u=p||[];if(e!=null){var y=o.type(e);e.length==null||y==="string"||y==="function"||y==="regexp"||o.isWindow(e)?M.call(u,e):o.merge(u,e)}return u},inArray:function(e,p){if(p.indexOf)return p.indexOf(e);for(var u=0,y=p.length;u<y;u++)if(p[u]===e)return u;return-1},merge:function(e,p){var u=e.length,y=0;if(typeof p.length==="number")for(var G=p.length;y<G;y++)e[u++]=p[y];else for(;p[y]!==H;)e[u++]=p[y++];e.length=u;return e},
grep:function(e,p,u){var y=[],G;u=!!u;for(var F=0,J=e.length;F<J;F++){G=!!p(e[F],F);u!==G&&y.push(e[F])}return y},map:function(e,p,u){for(var y=[],G,F=0,J=e.length;F<J;F++){G=p(e[F],F,u);if(G!=null)y[y.length]=G}return y.concat.apply([],y)},guid:1,proxy:function(e,p,u){if(arguments.length===2)if(typeof p==="string"){u=e;e=u[p];p=H}else if(p&&!o.isFunction(p)){u=p;p=H}if(!p&&e)p=function(){return e.apply(u||this,arguments)};if(e)p.guid=e.guid=e.guid||p.guid||o.guid++;return p},access:function(e,p,
u,y,G,F){var J=e.length;if(typeof p==="object"){for(var P in p)o.access(e,P,p[P],y,G,u);return e}if(u!==H){y=!F&&y&&o.isFunction(u);for(P=0;P<J;P++)G(e[P],p,y?u.call(e[P],P,G(e[P],p)):u,F);return e}return J?G(e[0],p):H},now:function(){return(new Date).getTime()},uaMatch:function(e){e=e.toLowerCase();e=t.exec(e)||a.exec(e)||b.exec(e)||e.indexOf("compatible")<0&&d.exec(e)||[];return{browser:e[1]||"",version:e[2]||"0"}},browser:{}});o.each("Boolean Number String Function Array Date RegExp Object".split(" "),
function(e,p){Q["[object "+p+"]"]=p.toLowerCase()});g=o.uaMatch(g);if(g.browser){o.browser[g.browser]=true;o.browser.version=g.version}if(o.browser.webkit)o.browser.safari=true;if(A)o.inArray=function(e,p){return A.call(p,e)};if(!/\s/.test("\u00a0")){w=/^[\s\xA0]+/;f=/[\s\xA0]+$/}E=o(v);if(v.addEventListener)r=function(){v.removeEventListener("DOMContentLoaded",r,false);o.ready()};else if(v.attachEvent)r=function(){if(v.readyState==="complete"){v.detachEvent("onreadystatechange",r);o.ready()}};return K.jQuery=
K.$=o}();(function(c){(function(){c.support={};var o=v.documentElement,C=v.createElement("script"),z=v.createElement("div"),E="script"+c.now();z.style.display="none";z.innerHTML="   <link/><table></table><a href='/a' style='color:red;float:left;opacity:.55;'>a</a><input type='checkbox'/>";var B=z.getElementsByTagName("*"),I=z.getElementsByTagName("a")[0],w=v.createElement("select"),f=w.appendChild(v.createElement("option"));if(!(!B||!B.length||!I)){c.support={leadingWhitespace:z.firstChild.nodeType===
3,tbody:!z.getElementsByTagName("tbody").length,htmlSerialize:!!z.getElementsByTagName("link").length,style:/red/.test(I.getAttribute("style")),hrefNormalized:I.getAttribute("href")==="/a",opacity:/^0.55$/.test(I.style.opacity),cssFloat:!!I.style.cssFloat,checkOn:z.getElementsByTagName("input")[0].value==="on",optSelected:f.selected,deleteExpando:true,optDisabled:false,checkClone:false,scriptEval:false,noCloneEvent:true,boxModel:null,inlineBlockNeedsLayout:false,shrinkWrapBlocks:false,reliableHiddenOffsets:true};
w.disabled=true;c.support.optDisabled=!f.disabled;C.type="text/javascript";try{C.appendChild(v.createTextNode("window."+E+"=1;"))}catch(j){}o.insertBefore(C,o.firstChild);if(K[E]){c.support.scriptEval=true;delete K[E]}try{delete C.test}catch(m){c.support.deleteExpando=false}o.removeChild(C);if(z.attachEvent&&z.fireEvent){z.attachEvent("onclick",function n(){c.support.noCloneEvent=false;z.detachEvent("onclick",n)});z.cloneNode(true).fireEvent("onclick")}z=v.createElement("div");z.innerHTML="<input type='radio' name='radiotest' checked='checked'/>";
o=v.createDocumentFragment();o.appendChild(z.firstChild);c.support.checkClone=o.cloneNode(true).cloneNode(true).lastChild.checked;c(function(){var n=v.createElement("div");n.style.width=n.style.paddingLeft="1px";v.body.appendChild(n);c.boxModel=c.support.boxModel=n.offsetWidth===2;if("zoom"in n.style){n.style.display="inline";n.style.zoom=1;c.support.inlineBlockNeedsLayout=n.offsetWidth===2;n.style.display="";n.innerHTML="<div style='width:4px;'></div>";c.support.shrinkWrapBlocks=n.offsetWidth!==
2}n.innerHTML="<table><tr><td style='padding:0;display:none'></td><td>t</td></tr></table>";var s=n.getElementsByTagName("td");c.support.reliableHiddenOffsets=s[0].offsetHeight===0;s[0].style.display="";s[1].style.display="none";c.support.reliableHiddenOffsets=c.support.reliableHiddenOffsets&&s[0].offsetHeight===0;n.innerHTML="";v.body.removeChild(n).style.display="none"});o=function(n){var s=v.createElement("div");n="on"+n;var h=n in s;if(!h){s.setAttribute(n,"return;");h=typeof s[n]==="function"}return h};
c.support.submitBubbles=o("submit");c.support.changeBubbles=o("change");o=C=z=B=I=null}})()})(L);L.extend({expando:"jQuery"+L.now(),noData:{embed:true,object:"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000",applet:true}});(function(c){var o=/[\n\t]/g,C=/\s+/,z=/\r/g,E=/^(?:href|src|style)$/,B=/^(?:button|input)$/i,I=/^(?:button|input|object|select|textarea)$/i,w=/^a(?:rea)?$/i,f=/^(?:radio|checkbox)$/i;c.props={"for":"htmlFor","class":"className",readonly:"readOnly",maxlength:"maxLength",cellspacing:"cellSpacing",
rowspan:"rowSpan",colspan:"colSpan",tabindex:"tabIndex",usemap:"useMap",frameborder:"frameBorder"};c.fn.extend({attr:function(j,m){return c.access(this,j,m,true,c.attr)},removeAttr:function(j){return this.each(function(){c.attr(this,j,"");this.nodeType===1&&this.removeAttribute(j)})},addClass:function(j){if(c.isFunction(j))return this.each(function(b){var d=c(this);d.addClass(j.call(this,b,d.attr("class")))});if(j&&typeof j==="string")for(var m=(j||"").split(C),n=0,s=this.length;n<s;n++){var h=this[n];
if(h.nodeType===1)if(h.className){for(var k=" "+h.className+" ",q=h.className,t=0,a=m.length;t<a;t++)if(k.indexOf(" "+m[t]+" ")<0)q+=" "+m[t];h.className=c.trim(q)}else h.className=j}return this},removeClass:function(j){if(c.isFunction(j))return this.each(function(a){var b=c(this);b.removeClass(j.call(this,a,b.attr("class")))});if(j&&typeof j==="string"||j===H)for(var m=(j||"").split(C),n=0,s=this.length;n<s;n++){var h=this[n];if(h.nodeType===1&&h.className)if(j){for(var k=(" "+h.className+" ").replace(o,
" "),q=0,t=m.length;q<t;q++)k=k.replace(" "+m[q]+" "," ");h.className=c.trim(k)}else h.className=""}return this},toggleClass:function(j,m){var n=typeof j,s=typeof m==="boolean";if(c.isFunction(j))return this.each(function(h){var k=c(this);k.toggleClass(j.call(this,h,k.attr("class"),m),m)});return this.each(function(){if(n==="string")for(var h,k=0,q=c(this),t=m,a=j.split(C);h=a[k++];){t=s?t:!q.hasClass(h);q[t?"addClass":"removeClass"](h)}else if(n==="undefined"||n==="boolean"){this.className&&c.data(this,
"__className__",this.className);this.className=this.className||j===false?"":c.data(this,"__className__")||""}})},hasClass:function(j){j=" "+j+" ";for(var m=0,n=this.length;m<n;m++)if((" "+this[m].className+" ").replace(o," ").indexOf(j)>-1)return true;return false},val:function(j){if(!arguments.length){var m=this[0];if(m){if(c.nodeName(m,"option")){var n=m.attributes.value;return!n||n.specified?m.value:m.text}if(c.nodeName(m,"select")){var s=m.selectedIndex;n=[];var h=m.options;m=m.type==="select-one";
if(s<0)return null;var k=m?s:0;for(s=m?s+1:h.length;k<s;k++){var q=h[k];if(q.selected&&(c.support.optDisabled?!q.disabled:q.getAttribute("disabled")===null)&&(!q.parentNode.disabled||!c.nodeName(q.parentNode,"optgroup"))){j=c(q).val();if(m)return j;n.push(j)}}return n}if(f.test(m.type)&&!c.support.checkOn)return m.getAttribute("value")===null?"on":m.value;return(m.value||"").replace(z,"")}return H}var t=c.isFunction(j);return this.each(function(a){var b=c(this),d=j;if(this.nodeType===1){if(t)d=j.call(this,
a,b.val());if(d==null)d="";else if(typeof d==="number")d+="";else if(c.isArray(d))d=c.map(d,function(i){return i==null?"":i+""});if(c.isArray(d)&&f.test(this.type))this.checked=c.inArray(b.val(),d)>=0;else if(c.nodeName(this,"select")){var g=c.makeArray(d);c("option",this).each(function(){this.selected=c.inArray(c(this).val(),g)>=0});if(!g.length)this.selectedIndex=-1}else this.value=d}})}});c.extend({attrFn:{val:true,css:true,html:true,text:true,data:true,width:true,height:true,offset:true},attr:function(j,
m,n,s){if(!j||j.nodeType===3||j.nodeType===8)return H;if(s&&m in c.attrFn)return c(j)[m](n);s=j.nodeType!==1||!c.isXMLDoc(j);var h=n!==H;m=s&&c.props[m]||m;var k=E.test(m);if((m in j||j[m]!==H)&&s&&!k){if(h){m==="type"&&B.test(j.nodeName)&&j.parentNode&&c.error("type property can't be changed");if(n===null)j.nodeType===1&&j.removeAttribute(m);else j[m]=n}if(c.nodeName(j,"form")&&j.getAttributeNode(m))return j.getAttributeNode(m).nodeValue;if(m==="tabIndex")return(m=j.getAttributeNode("tabIndex"))&&
m.specified?m.value:I.test(j.nodeName)||w.test(j.nodeName)&&j.href?0:H;return j[m]}if(!c.support.style&&s&&m==="style"){if(h)j.style.cssText=""+n;return j.style.cssText}h&&j.setAttribute(m,""+n);if(!j.attributes[m]&&j.hasAttribute&&!j.hasAttribute(m))return H;j=!c.support.hrefNormalized&&s&&k?j.getAttribute(m,2):j.getAttribute(m);return j===null?H:j}})})(L);(function(){function c(a,b,d,g,i,l){i=0;for(var r=g.length;i<r;i++){var x=g[i];if(x){var D=false;for(x=x[a];x;){if(x.sizcache===d){D=g[x.sizset];
break}if(x.nodeType===1&&!l){x.sizcache=d;x.sizset=i}if(x.nodeName.toLowerCase()===b){D=x;break}x=x[a]}g[i]=D}}}function o(a,b,d,g,i,l){i=0;for(var r=g.length;i<r;i++){var x=g[i];if(x){var D=false;for(x=x[a];x;){if(x.sizcache===d){D=g[x.sizset];break}if(x.nodeType===1){if(!l){x.sizcache=d;x.sizset=i}if(typeof b!=="string"){if(x===b){D=true;break}}else if(w.filter(b,[x]).length>0){D=x;break}}x=x[a]}g[i]=D}}}var C=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^\[\]]*\]|['"][^'"]*['"]|[^\[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,
z=0,E=Object.prototype.toString,B=false,I=true;[0,0].sort(function(){I=false;return 0});var w=function(a,b,d,g){d=d||[];var i=b=b||v;if(b.nodeType!==1&&b.nodeType!==9)return[];if(!a||typeof a!=="string")return d;var l,r,x,D,M,N=true,O=w.isXML(b),A=[],Q=a;do{C.exec("");if(l=C.exec(Q)){Q=l[3];A.push(l[1]);if(l[2]){D=l[3];break}}}while(l);if(A.length>1&&j.exec(a))if(A.length===2&&f.relative[A[0]])r=t(A[0]+A[1],b);else for(r=f.relative[A[0]]?[b]:w(A.shift(),b);A.length;){a=A.shift();if(f.relative[a])a+=
A.shift();r=t(a,r)}else{if(!g&&A.length>1&&b.nodeType===9&&!O&&f.match.ID.test(A[0])&&!f.match.ID.test(A[A.length-1])){l=w.find(A.shift(),b,O);b=l.expr?w.filter(l.expr,l.set)[0]:l.set[0]}if(b){l=g?{expr:A.pop(),set:s(g)}:w.find(A.pop(),A.length===1&&(A[0]==="~"||A[0]==="+")&&b.parentNode?b.parentNode:b,O);r=l.expr?w.filter(l.expr,l.set):l.set;if(A.length>0)x=s(r);else N=false;for(;A.length;){l=M=A.pop();if(f.relative[M])l=A.pop();else M="";if(l==null)l=b;f.relative[M](x,l,O)}}else x=[]}x||(x=r);x||
w.error(M||a);if(E.call(x)==="[object Array]")if(N)if(b&&b.nodeType===1)for(a=0;x[a]!=null;a++){if(x[a]&&(x[a]===true||x[a].nodeType===1&&w.contains(b,x[a])))d.push(r[a])}else for(a=0;x[a]!=null;a++)x[a]&&x[a].nodeType===1&&d.push(r[a]);else d.push.apply(d,x);else s(x,d);if(D){w(D,i,d,g);w.uniqueSort(d)}return d};w.uniqueSort=function(a){if(k){B=I;a.sort(k);if(B)for(var b=1;b<a.length;b++)a[b]===a[b-1]&&a.splice(b--,1)}return a};w.matches=function(a,b){return w(a,null,null,b)};w.matchesSelector=function(a,
b){return w(b,null,null,[a]).length>0};w.find=function(a,b,d){var g;if(!a)return[];for(var i=0,l=f.order.length;i<l;i++){var r,x=f.order[i];if(r=f.leftMatch[x].exec(a)){var D=r[1];r.splice(1,1);if(D.substr(D.length-1)!=="\\"){r[1]=(r[1]||"").replace(/\\/g,"");g=f.find[x](r,b,d);if(g!=null){a=a.replace(f.match[x],"");break}}}}g||(g=b.getElementsByTagName("*"));return{set:g,expr:a}};w.filter=function(a,b,d,g){for(var i,l,r=a,x=[],D=b,M=b&&b[0]&&w.isXML(b[0]);a&&b.length;){for(var N in f.filter)if((i=
f.leftMatch[N].exec(a))!=null&&i[2]){var O,A,Q=f.filter[N];A=i[1];l=false;i.splice(1,1);if(A.substr(A.length-1)!=="\\"){if(D===x)x=[];if(f.preFilter[N])if(i=f.preFilter[N](i,D,d,x,g,M)){if(i===true)continue}else l=O=true;if(i)for(var e=0;(A=D[e])!=null;e++)if(A){O=Q(A,i,e,D);var p=g^!!O;if(d&&O!=null)if(p)l=true;else D[e]=false;else if(p){x.push(A);l=true}}if(O!==H){d||(D=x);a=a.replace(f.match[N],"");if(!l)return[];break}}}if(a===r)if(l==null)w.error(a);else break;r=a}return D};w.error=function(a){throw"Syntax error, unrecognized expression: "+
a;};var f=w.selectors={order:["ID","NAME","TAG"],match:{ID:/#((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,CLASS:/\.((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u00c0-\uFFFF\-]|\\.)+)['"]*\]/,ATTR:/\[\s*((?:[\w\u00c0-\uFFFF\-]|\\.)+)\s*(?:(\S?=)\s*(['"]*)(.*?)\3|)\s*\]/,TAG:/^((?:[\w\u00c0-\uFFFF\*\-]|\\.)+)/,CHILD:/:(only|nth|last|first)-child(?:\((even|odd|[\dn+\-]*)\))?/,POS:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^\-]|$)/,PSEUDO:/:((?:[\w\u00c0-\uFFFF\-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},
leftMatch:{},attrMap:{"class":"className","for":"htmlFor"},attrHandle:{href:function(a){return a.getAttribute("href")}},relative:{"+":function(a,b){var d=typeof b==="string",g=d&&!/\W/.test(b);d=d&&!g;if(g)b=b.toLowerCase();g=0;for(var i=a.length,l;g<i;g++)if(l=a[g]){for(;(l=l.previousSibling)&&l.nodeType!==1;);a[g]=d||l&&l.nodeName.toLowerCase()===b?l||false:l===b}d&&w.filter(b,a,true)},">":function(a,b){var d,g=typeof b==="string",i=0,l=a.length;if(g&&!/\W/.test(b))for(b=b.toLowerCase();i<l;i++){if(d=
a[i]){d=d.parentNode;a[i]=d.nodeName.toLowerCase()===b?d:false}}else{for(;i<l;i++)if(d=a[i])a[i]=g?d.parentNode:d.parentNode===b;g&&w.filter(b,a,true)}},"":function(a,b,d){var g,i=z++,l=o;if(typeof b==="string"&&!/\W/.test(b)){g=b=b.toLowerCase();l=c}l("parentNode",b,i,a,g,d)},"~":function(a,b,d){var g,i=z++,l=o;if(typeof b==="string"&&!/\W/.test(b)){g=b=b.toLowerCase();l=c}l("previousSibling",b,i,a,g,d)}},find:{ID:function(a,b,d){if(typeof b.getElementById!=="undefined"&&!d)return(a=b.getElementById(a[1]))&&
a.parentNode?[a]:[]},NAME:function(a,b){if(typeof b.getElementsByName!=="undefined"){for(var d=[],g=b.getElementsByName(a[1]),i=0,l=g.length;i<l;i++)g[i].getAttribute("name")===a[1]&&d.push(g[i]);return d.length===0?null:d}},TAG:function(a,b){return b.getElementsByTagName(a[1])}},preFilter:{CLASS:function(a,b,d,g,i,l){a=" "+a[1].replace(/\\/g,"")+" ";if(l)return a;l=0;for(var r;(r=b[l])!=null;l++)if(r)if(i^(r.className&&(" "+r.className+" ").replace(/[\t\n]/g," ").indexOf(a)>=0))d||g.push(r);else if(d)b[l]=
false;return false},ID:function(a){return a[1].replace(/\\/g,"")},TAG:function(a){return a[1].toLowerCase()},CHILD:function(a){if(a[1]==="nth"){var b=/(-?)(\d*)n((?:\+|-)?\d*)/.exec(a[2]==="even"&&"2n"||a[2]==="odd"&&"2n+1"||!/\D/.test(a[2])&&"0n+"+a[2]||a[2]);a[2]=b[1]+(b[2]||1)-0;a[3]=b[3]-0}a[0]=z++;return a},ATTR:function(a,b,d,g,i,l){b=a[1].replace(/\\/g,"");if(!l&&f.attrMap[b])a[1]=f.attrMap[b];if(a[2]==="~=")a[4]=" "+a[4]+" ";return a},PSEUDO:function(a,b,d,g,i){if(a[1]==="not")if((C.exec(a[3])||
"").length>1||/^\w/.test(a[3]))a[3]=w(a[3],null,null,b);else{a=w.filter(a[3],b,d,true^i);d||g.push.apply(g,a);return false}else if(f.match.POS.test(a[0])||f.match.CHILD.test(a[0]))return true;return a},POS:function(a){a.unshift(true);return a}},filters:{enabled:function(a){return a.disabled===false&&a.type!=="hidden"},disabled:function(a){return a.disabled===true},checked:function(a){return a.checked===true},selected:function(a){return a.selected===true},parent:function(a){return!!a.firstChild},empty:function(a){return!a.firstChild},
has:function(a,b,d){return!!w(d[3],a).length},header:function(a){return/h\d/i.test(a.nodeName)},text:function(a){return"text"===a.type},radio:function(a){return"radio"===a.type},checkbox:function(a){return"checkbox"===a.type},file:function(a){return"file"===a.type},password:function(a){return"password"===a.type},submit:function(a){return"submit"===a.type},image:function(a){return"image"===a.type},reset:function(a){return"reset"===a.type},button:function(a){return"button"===a.type||a.nodeName.toLowerCase()===
"button"},input:function(a){return/input|select|textarea|button/i.test(a.nodeName)}},setFilters:{first:function(a,b){return b===0},last:function(a,b,d,g){return b===g.length-1},even:function(a,b){return b%2===0},odd:function(a,b){return b%2===1},lt:function(a,b,d){return b<d[3]-0},gt:function(a,b,d){return b>d[3]-0},nth:function(a,b,d){return d[3]-0===b},eq:function(a,b,d){return d[3]-0===b}},filter:{PSEUDO:function(a,b,d,g){var i=b[1],l=f.filters[i];if(l)return l(a,d,b,g);else if(i==="contains")return(a.textContent||
a.innerText||w.getText([a])||"").indexOf(b[3])>=0;else if(i==="not"){b=b[3];d=0;for(g=b.length;d<g;d++)if(b[d]===a)return false;return true}else w.error("Syntax error, unrecognized expression: "+i)},CHILD:function(a,b){var d=b[1],g=a;switch(d){case "only":case "first":for(;g=g.previousSibling;)if(g.nodeType===1)return false;if(d==="first")return true;g=a;case "last":for(;g=g.nextSibling;)if(g.nodeType===1)return false;return true;case "nth":d=b[2];var i=b[3];if(d===1&&i===0)return true;var l=b[0],
r=a.parentNode;if(r&&(r.sizcache!==l||!a.nodeIndex)){var x=0;for(g=r.firstChild;g;g=g.nextSibling)if(g.nodeType===1)g.nodeIndex=++x;r.sizcache=l}g=a.nodeIndex-i;return d===0?g===0:g%d===0&&g/d>=0}},ID:function(a,b){return a.nodeType===1&&a.getAttribute("id")===b},TAG:function(a,b){return b==="*"&&a.nodeType===1||a.nodeName.toLowerCase()===b},CLASS:function(a,b){return(" "+(a.className||a.getAttribute("class"))+" ").indexOf(b)>-1},ATTR:function(a,b){var d=b[1];d=f.attrHandle[d]?f.attrHandle[d](a):
a[d]!=null?a[d]:a.getAttribute(d);var g=d+"",i=b[2],l=b[4];return d==null?i==="!=":i==="="?g===l:i==="*="?g.indexOf(l)>=0:i==="~="?(" "+g+" ").indexOf(l)>=0:!l?g&&d!==false:i==="!="?g!==l:i==="^="?g.indexOf(l)===0:i==="$="?g.substr(g.length-l.length)===l:i==="|="?g===l||g.substr(0,l.length+1)===l+"-":false},POS:function(a,b,d,g){var i=f.setFilters[b[2]];if(i)return i(a,d,b,g)}}},j=f.match.POS,m=function(a,b){return"\\"+(b-0+1)},n;for(n in f.match){f.match[n]=RegExp(f.match[n].source+/(?![^\[]*\])(?![^\(]*\))/.source);
f.leftMatch[n]=RegExp(/(^(?:.|\r|\n)*?)/.source+f.match[n].source.replace(/\\(\d+)/g,m))}var s=function(a,b){a=Array.prototype.slice.call(a,0);if(b){b.push.apply(b,a);return b}return a};try{Array.prototype.slice.call(v.documentElement.childNodes,0)}catch(h){s=function(a,b){var d=0,g=b||[];if(E.call(a)==="[object Array]")Array.prototype.push.apply(g,a);else if(typeof a.length==="number")for(var i=a.length;d<i;d++)g.push(a[d]);else for(;a[d];d++)g.push(a[d]);return g}}var k,q;if(v.documentElement.compareDocumentPosition)k=
function(a,b){if(a===b){B=true;return 0}if(!a.compareDocumentPosition||!b.compareDocumentPosition)return a.compareDocumentPosition?-1:1;return a.compareDocumentPosition(b)&4?-1:1};else{k=function(a,b){var d,g,i=[],l=[];d=a.parentNode;g=b.parentNode;var r=d;if(a===b){B=true;return 0}else if(d===g)return q(a,b);else if(d){if(!g)return 1}else return-1;for(;r;){i.unshift(r);r=r.parentNode}for(r=g;r;){l.unshift(r);r=r.parentNode}d=i.length;g=l.length;for(r=0;r<d&&r<g;r++)if(i[r]!==l[r])return q(i[r],l[r]);
return r===d?q(a,l[r],-1):q(i[r],b,1)};q=function(a,b,d){if(a===b)return d;for(a=a.nextSibling;a;){if(a===b)return-1;a=a.nextSibling}return 1}}w.getText=function(a){for(var b="",d,g=0;a[g];g++){d=a[g];if(d.nodeType===3||d.nodeType===4)b+=d.nodeValue;else if(d.nodeType!==8)b+=w.getText(d.childNodes)}return b};(function(){var a=v.createElement("div"),b="script"+(new Date).getTime(),d=v.documentElement;a.innerHTML="<a name='"+b+"'/>";d.insertBefore(a,d.firstChild);if(v.getElementById(b)){f.find.ID=function(g,
i,l){if(typeof i.getElementById!=="undefined"&&!l)return(i=i.getElementById(g[1]))?i.id===g[1]||typeof i.getAttributeNode!=="undefined"&&i.getAttributeNode("id").nodeValue===g[1]?[i]:H:[]};f.filter.ID=function(g,i){var l=typeof g.getAttributeNode!=="undefined"&&g.getAttributeNode("id");return g.nodeType===1&&l&&l.nodeValue===i}}d.removeChild(a);d=a=null})();(function(){var a=v.createElement("div");a.appendChild(v.createComment(""));if(a.getElementsByTagName("*").length>0)f.find.TAG=function(b,d){var g=
d.getElementsByTagName(b[1]);if(b[1]==="*"){for(var i=[],l=0;g[l];l++)g[l].nodeType===1&&i.push(g[l]);g=i}return g};a.innerHTML="<a href='#'></a>";if(a.firstChild&&typeof a.firstChild.getAttribute!=="undefined"&&a.firstChild.getAttribute("href")!=="#")f.attrHandle.href=function(b){return b.getAttribute("href",2)};a=null})();v.querySelectorAll&&function(){var a=w,b=v.createElement("div");b.innerHTML="<p class='TEST'></p>";if(!(b.querySelectorAll&&b.querySelectorAll(".TEST").length===0)){w=function(g,
i,l,r){i=i||v;g=g.replace(/\=\s*([^'"\]]*)\s*\]/g,"='$1']");if(!r&&!w.isXML(i))if(i.nodeType===9)try{return s(i.querySelectorAll(g),l)}catch(x){}else if(i.nodeType===1&&i.nodeName.toLowerCase()!=="object"){var D=i.getAttribute("id"),M=D||"__sizzle__";D||i.setAttribute("id",M);try{return s(i.querySelectorAll("#"+M+" "+g),l)}catch(N){}finally{D||i.removeAttribute("id")}}return a(g,i,l,r)};for(var d in a)w[d]=a[d];b=null}}();(function(){var a=v.documentElement,b=a.matchesSelector||a.mozMatchesSelector||
a.webkitMatchesSelector||a.msMatchesSelector,d=false;try{b.call(v.documentElement,"[test!='']:sizzle")}catch(g){d=true}if(b)w.matchesSelector=function(i,l){l=l.replace(/\=\s*([^'"\]]*)\s*\]/g,"='$1']");if(!w.isXML(i))try{if(d||!f.match.PSEUDO.test(l)&&!/!=/.test(l))return b.call(i,l)}catch(r){}return w(l,null,null,[i]).length>0}})();(function(){var a=v.createElement("div");a.innerHTML="<div class='test e'></div><div class='test'></div>";if(!(!a.getElementsByClassName||a.getElementsByClassName("e").length===
0)){a.lastChild.className="e";if(a.getElementsByClassName("e").length!==1){f.order.splice(1,0,"CLASS");f.find.CLASS=function(b,d,g){if(typeof d.getElementsByClassName!=="undefined"&&!g)return d.getElementsByClassName(b[1])};a=null}}})();w.contains=v.documentElement.contains?function(a,b){return a!==b&&(a.contains?a.contains(b):true)}:v.documentElement.compareDocumentPosition?function(a,b){return!!(a.compareDocumentPosition(b)&16)}:function(){return false};w.isXML=function(a){return(a=(a?a.ownerDocument||
a:0).documentElement)?a.nodeName!=="HTML":false};var t=function(a,b){for(var d,g=[],i="",l=b.nodeType?[b]:b;d=f.match.PSEUDO.exec(a);){i+=d[0];a=a.replace(f.match.PSEUDO,"")}a=f.relative[a]?a+"*":a;d=0;for(var r=l.length;d<r;d++)w(a,l[d],g);return w.filter(i,g)};L.find=w;L.expr=w.selectors;L.expr[":"]=L.expr.filters;L.unique=w.uniqueSort;L.text=w.getText;L.isXMLDoc=w.isXML;L.contains=w.contains})();(function(c){function o(f,j,m){if(c.isFunction(j))return c.grep(f,function(s,h){return!!j.call(s,h,
s)===m});else if(j.nodeType)return c.grep(f,function(s){return s===j===m});else if(typeof j==="string"){var n=c.grep(f,function(s){return s.nodeType===1});if(B.test(j))return c.filter(j,n,!m);else j=c.filter(j,n)}return c.grep(f,function(s){return c.inArray(s,j)>=0===m})}var C=/Until$/,z=/^(?:parents|prevUntil|prevAll)/,E=/,/,B=/^.[^:#\[\.,]*$/,I=Array.prototype.slice,w=c.expr.match.POS;c.fn.extend({find:function(f){for(var j=this.pushStack("","find",f),m=0,n=0,s=this.length;n<s;n++){m=j.length;c.find(f,
this[n],j);if(n>0)for(var h=m;h<j.length;h++)for(var k=0;k<m;k++)if(j[k]===j[h]){j.splice(h--,1);break}}return j},has:function(f){var j=c(f);return this.filter(function(){for(var m=0,n=j.length;m<n;m++)if(c.contains(this,j[m]))return true})},not:function(f){return this.pushStack(o(this,f,false),"not",f)},filter:function(f){return this.pushStack(o(this,f,true),"filter",f)},is:function(f){return!!f&&c.filter(f,this).length>0},closest:function(f,j){var m=[],n,s,h=this[0];if(c.isArray(f)){var k,q={},
t=1;if(h&&f.length){n=0;for(s=f.length;n<s;n++){k=f[n];q[k]||(q[k]=c.expr.match.POS.test(k)?c(k,j||this.context):k)}for(;h&&h.ownerDocument&&h!==j;){for(k in q){n=q[k];if(n.jquery?n.index(h)>-1:c(h).is(n))m.push({selector:k,elem:h,level:t})}h=h.parentNode;t++}}return m}k=w.test(f)?c(f,j||this.context):null;n=0;for(s=this.length;n<s;n++)for(h=this[n];h;)if(k?k.index(h)>-1:c.find.matchesSelector(h,f)){m.push(h);break}else{h=h.parentNode;if(!h||!h.ownerDocument||h===j)break}m=m.length>1?c.unique(m):
m;return this.pushStack(m,"closest",f)},index:function(f){if(!f||typeof f==="string")return c.inArray(this[0],f?c(f):this.parent().children());return c.inArray(f.jquery?f[0]:f,this)},add:function(f,j){var m=typeof f==="string"?c(f,j||this.context):c.makeArray(f),n=c.merge(this.get(),m);return this.pushStack(!m[0]||!m[0].parentNode||m[0].parentNode.nodeType===11||!n[0]||!n[0].parentNode||n[0].parentNode.nodeType===11?n:c.unique(n))},andSelf:function(){return this.add(this.prevObject)}});c.each({parent:function(f){return(f=
f.parentNode)&&f.nodeType!==11?f:null},parents:function(f){return c.dir(f,"parentNode")},parentsUntil:function(f,j,m){return c.dir(f,"parentNode",m)},next:function(f){return c.nth(f,2,"nextSibling")},prev:function(f){return c.nth(f,2,"previousSibling")},nextAll:function(f){return c.dir(f,"nextSibling")},prevAll:function(f){return c.dir(f,"previousSibling")},nextUntil:function(f,j,m){return c.dir(f,"nextSibling",m)},prevUntil:function(f,j,m){return c.dir(f,"previousSibling",m)},siblings:function(f){return c.sibling(f.parentNode.firstChild,
f)},children:function(f){return c.sibling(f.firstChild)},contents:function(f){return c.nodeName(f,"iframe")?f.contentDocument||f.contentWindow.document:c.makeArray(f.childNodes)}},function(f,j){c.fn[f]=function(m,n){var s=c.map(this,j,m);C.test(f)||(n=m);if(n&&typeof n==="string")s=c.filter(n,s);s=this.length>1?c.unique(s):s;if((this.length>1||E.test(n))&&z.test(f))s=s.reverse();return this.pushStack(s,f,I.call(arguments).join(","))}});c.extend({filter:function(f,j,m){if(m)f=":not("+f+")";return j.length===
1?c.find.matchesSelector(j[0],f)?[j[0]]:[]:c.find.matches(f,j)},dir:function(f,j,m){var n=[];for(f=f[j];f&&f.nodeType!==9&&(m===H||f.nodeType!==1||!c(f).is(m));){f.nodeType===1&&n.push(f);f=f[j]}return n},nth:function(f,j,m){j=j||1;for(var n=0;f;f=f[m])if(f.nodeType===1&&++n===j)break;return f},sibling:function(f,j){for(var m=[];f;f=f.nextSibling)f.nodeType===1&&f!==j&&m.push(f);return m}})})(L);(function(c){function o(h,k){var q=0;k.each(function(){if(this.nodeName===(h[q]&&h[q].nodeName)){var t=
c.data(h[q++]),a=c.data(this,t);if(t=t&&t.events){delete a.handle;a.events={};for(var b in t)for(var d in t[b])c.event.add(this,b,t[b][d],t[b][d].data)}}})}function C(h,k){k.src?c.ajax({url:k.src,async:false,dataType:"script"}):c.globalEval(k.text||k.textContent||k.innerHTML||"");k.parentNode&&k.parentNode.removeChild(k)}var z=/ jQuery\d+="(?:\d+|null)"/g,E=/^\s+/,B=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,I=/<([\w:]+)/,w=/<tbody/i,f=/<|&#?\w+;/,j=/<(?:script|object|embed|option|style)/i,
m=/checked\s*(?:[^=]|=\s*.checked.)/i,n=/\=([^="'>\s]+\/)>/g,s={option:[1,"<select multiple='multiple'>","</select>"],legend:[1,"<fieldset>","</fieldset>"],thead:[1,"<table>","</table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],col:[2,"<table><tbody></tbody><colgroup>","</colgroup></table>"],area:[1,"<map>","</map>"],_default:[0,"",""]};s.optgroup=s.option;s.tbody=s.tfoot=s.colgroup=s.caption=s.thead;s.th=s.td;if(!c.support.htmlSerialize)s._default=
[1,"div<div>","</div>"];c.fn.extend({text:function(h){if(c.isFunction(h))return this.each(function(k){var q=c(this);q.text(h.call(this,k,q.text()))});if(typeof h!=="object"&&h!==H)return this.empty().append((this[0]&&this[0].ownerDocument||v).createTextNode(h));return c.text(this)},wrapAll:function(h){if(c.isFunction(h))return this.each(function(q){c(this).wrapAll(h.call(this,q))});if(this[0]){var k=c(h,this[0].ownerDocument).eq(0).clone(true);this[0].parentNode&&k.insertBefore(this[0]);k.map(function(){for(var q=
this;q.firstChild&&q.firstChild.nodeType===1;)q=q.firstChild;return q}).append(this)}return this},wrapInner:function(h){if(c.isFunction(h))return this.each(function(k){c(this).wrapInner(h.call(this,k))});return this.each(function(){var k=c(this),q=k.contents();q.length?q.wrapAll(h):k.append(h)})},wrap:function(h){return this.each(function(){c(this).wrapAll(h)})},unwrap:function(){return this.parent().each(function(){c.nodeName(this,"body")||c(this).replaceWith(this.childNodes)}).end()},append:function(){return this.domManip(arguments,
true,function(h){this.nodeType===1&&this.appendChild(h)})},prepend:function(){return this.domManip(arguments,true,function(h){this.nodeType===1&&this.insertBefore(h,this.firstChild)})},before:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,false,function(k){this.parentNode.insertBefore(k,this)});else if(arguments.length){var h=c(arguments[0]);h.push.apply(h,this.toArray());return this.pushStack(h,"before",arguments)}},after:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,
false,function(k){this.parentNode.insertBefore(k,this.nextSibling)});else if(arguments.length){var h=this.pushStack(this,"after",arguments);h.push.apply(h,c(arguments[0]).toArray());return h}},remove:function(h,k){for(var q=0,t;(t=this[q])!=null;q++)if(!h||c.filter(h,[t]).length){if(!k&&t.nodeType===1){c.cleanData(t.getElementsByTagName("*"));c.cleanData([t])}t.parentNode&&t.parentNode.removeChild(t)}return this},empty:function(){for(var h=0,k;(k=this[h])!=null;h++)for(k.nodeType===1&&c.cleanData(k.getElementsByTagName("*"));k.firstChild;)k.removeChild(k.firstChild);
return this},clone:function(h){var k=this.map(function(){if(!c.support.noCloneEvent&&!c.isXMLDoc(this)){var q=this.outerHTML,t=this.ownerDocument;if(!q){q=t.createElement("div");q.appendChild(this.cloneNode(true));q=q.innerHTML}return c.clean([q.replace(z,"").replace(n,'="$1">').replace(E,"")],t)[0]}else return this.cloneNode(true)});if(h===true){o(this,k);o(this.find("*"),k.find("*"))}return k},html:function(h){if(h===H)return this[0]&&this[0].nodeType===1?this[0].innerHTML.replace(z,""):null;else if(typeof h===
"string"&&!j.test(h)&&(c.support.leadingWhitespace||!E.test(h))&&!s[(I.exec(h)||["",""])[1].toLowerCase()]){h=h.replace(B,"<$1></$2>");try{for(var k=0,q=this.length;k<q;k++)if(this[k].nodeType===1){c.cleanData(this[k].getElementsByTagName("*"));this[k].innerHTML=h}}catch(t){this.empty().append(h)}}else c.isFunction(h)?this.each(function(a){var b=c(this);b.html(h.call(this,a,b.html()))}):this.empty().append(h);return this},replaceWith:function(h){if(this[0]&&this[0].parentNode){if(c.isFunction(h))return this.each(function(k){var q=
c(this),t=q.html();q.replaceWith(h.call(this,k,t))});if(typeof h!=="string")h=c(h).detach();return this.each(function(){var k=this.nextSibling,q=this.parentNode;c(this).remove();k?c(k).before(h):c(q).append(h)})}else return this.pushStack(c(c.isFunction(h)?h():h),"replaceWith",h)},detach:function(h){return this.remove(h,true)},domManip:function(h,k,q){var t,a,b,d=h[0],g=[];if(!c.support.checkClone&&arguments.length===3&&typeof d==="string"&&m.test(d))return this.each(function(){c(this).domManip(h,
k,q,true)});if(c.isFunction(d))return this.each(function(l){var r=c(this);h[0]=d.call(this,l,k?r.html():H);r.domManip(h,k,q)});if(this[0]){t=d&&d.parentNode;t=c.support.parentNode&&t&&t.nodeType===11&&t.childNodes.length===this.length?{fragment:t}:c.buildFragment(h,this,g);b=t.fragment;if(a=b.childNodes.length===1?b=b.firstChild:b.firstChild){k=k&&c.nodeName(a,"tr");a=0;for(var i=this.length;a<i;a++)q.call(k?c.nodeName(this[a],"table")?this[a].getElementsByTagName("tbody")[0]||this[a].appendChild(this[a].ownerDocument.createElement("tbody")):
this[a]:this[a],a>0||t.cacheable||this.length>1?b.cloneNode(true):b)}g.length&&c.each(g,C)}return this}});c.buildFragment=function(h,k,q){var t,a,b;k=k&&k[0]?k[0].ownerDocument||k[0]:v;if(h.length===1&&typeof h[0]==="string"&&h[0].length<512&&k===v&&!j.test(h[0])&&(c.support.checkClone||!m.test(h[0]))){a=true;if(b=c.fragments[h[0]])if(b!==1)t=b}if(!t){t=k.createDocumentFragment();c.clean(h,k,t,q)}if(a)c.fragments[h[0]]=b?t:1;return{fragment:t,cacheable:a}};c.fragments={};c.each({appendTo:"append",
prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(h,k){c.fn[h]=function(q){var t=[];q=c(q);var a=this.length===1&&this[0].parentNode;if(a&&a.nodeType===11&&a.childNodes.length===1&&q.length===1){q[k](this[0]);return this}else{a=0;for(var b=q.length;a<b;a++){var d=(a>0?this.clone(true):this).get();c(q[a])[k](d);t=t.concat(d)}return this.pushStack(t,h,q.selector)}}});c.extend({clean:function(h,k,q,t){k=k||v;if(typeof k.createElement==="undefined")k=k.ownerDocument||
k[0]&&k[0].ownerDocument||v;for(var a=[],b=0,d;(d=h[b])!=null;b++){if(typeof d==="number")d+="";if(d){if(typeof d==="string"&&!f.test(d))d=k.createTextNode(d);else if(typeof d==="string"){d=d.replace(B,"<$1></$2>");var g=(I.exec(d)||["",""])[1].toLowerCase(),i=s[g]||s._default,l=i[0],r=k.createElement("div");for(r.innerHTML=i[1]+d+i[2];l--;)r=r.lastChild;if(!c.support.tbody){l=w.test(d);g=g==="table"&&!l?r.firstChild&&r.firstChild.childNodes:i[1]==="<table>"&&!l?r.childNodes:[];for(i=g.length-1;i>=
0;--i)c.nodeName(g[i],"tbody")&&!g[i].childNodes.length&&g[i].parentNode.removeChild(g[i])}!c.support.leadingWhitespace&&E.test(d)&&r.insertBefore(k.createTextNode(E.exec(d)[0]),r.firstChild);d=r.childNodes}if(d.nodeType)a.push(d);else a=c.merge(a,d)}}if(q)for(b=0;a[b];b++)if(t&&c.nodeName(a[b],"script")&&(!a[b].type||a[b].type.toLowerCase()==="text/javascript"))t.push(a[b].parentNode?a[b].parentNode.removeChild(a[b]):a[b]);else{a[b].nodeType===1&&a.splice.apply(a,[b+1,0].concat(c.makeArray(a[b].getElementsByTagName("script"))));
q.appendChild(a[b])}return a},cleanData:function(h){for(var k,q=c.cache,t=c.support.deleteExpando,a=0,b;(b=h[a])!=null;a++)if(!(b.nodeName&&c.noData[b.nodeName.toLowerCase()]))if(k=b[c.expando]){if(t)delete b[c.expando];else b.removeAttribute&&b.removeAttribute(c.expando);delete q[k]}}})})(L);(function(c){c.each(["Height","Width"],function(o,C){var z=C.toLowerCase();c.fn["inner"+C]=function(){return this[0]?parseFloat(c.css(this[0],z,"padding")):null};c.fn["outer"+C]=function(E){return this[0]?parseFloat(c.css(this[0],
z,E?"margin":"border")):null};c.fn[z]=function(E){var B=this[0];if(!B)return E==null?null:this;if(c.isFunction(E))return this.each(function(w){var f=c(this);f[z](E.call(this,w,f[z]()))});if(c.isWindow(B))return B.document.compatMode==="CSS1Compat"&&B.document.documentElement["client"+C]||B.document.body["client"+C];else if(B.nodeType===9)return Math.max(B.documentElement["client"+C],B.body["scroll"+C],B.documentElement["scroll"+C],B.body["offset"+C],B.documentElement["offset"+C]);else if(E===H){B=
c.css(B,z);var I=parseFloat(B);return c.isNaN(I)?B:I}else return this.css(z,typeof E==="string"?E:E+"px")}})})(L)})(window);
